### ISSUE TITLE
Add some keyboard shortcuts or hotkeys

### ISSUE THREAD

**Issue by doggy8088** [nrwl/angular-console#103]
For example:

![image](https://user-images.githubusercontent.com/88981/43938982-80c040cc-9c99-11e8-832b-4e269cb7ab5b.png)

* `Ctrl-1`: switch to **Projects**
* `Ctrl-2`: switch to **Generate Code**
* `Ctrl-3`: switch to **Run Tasks**
* `Ctrl-4`: switch to **Add/Remove CLI Extensions**
* ArrowDown / ArrowUp: move cursor up and down of the items
* `/`: Jump to Filter

![image](https://user-images.githubusercontent.com/88981/43938969-67a7f3c8-9c99-11e8-94c3-29d0597524a1.png)

* `Alt-A`: hit **Add** button
* `Alt-C`: hit **Cancel** button
* `Escape`: back to go back to previous page

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. We will be adding keyboard shortcuts to our vscode release shortly
