### ISSUE TITLE
[Feature Request] Allow creation of component in sub-directory

### ISSUE THREAD

**Issue by joostme** [nrwl/angular-console#109]
Currently you have to provide a name for new components including sub-directories for the component to be created in a sub-directory.

For example:
I want to create `info` component inside the `entitiy/detail` folder.

I would have to name the component `entity/detail/info`.

**Feature Request:**
Allow option to choose the directory a new component is created in

**Comment by mrmeku** [comment]
This is a limitation of the Angular CLI rather than angular console. Please file your bug against the CLI itself: https://github.com/angular/angular-cli
