### ISSUE TITLE
Feature: Available Extension Discovery

### ISSUE THREAD

**Issue by cgatian** [nrwl/angular-console#110]
Working in the enterprise we own our own schematics on a private npm feed. It would be nice if you could configure a discovery endpoint that the application queried to provide additional information to Angular Console, such as populating the Available Extensions tab.

**Comment by mrmeku** [comment]
Right now we encourage all with public extensions to submit a PR to our repo to add them to our list. As we don't have an endpoint and instead have a hardcoded list we won't be able to fulfill this request

**Comment by cgatian** [comment]
@mrmeku that was the point of this issue.  We host our packages internally and it would be nice to have this list editable so we can include our private schematics
