### ISSUE TITLE
Unsigned executable triggers virus protection

### ISSUE THREAD

**Issue by avaramis** [nrwl/angular-console#111]
Norton won't let me download this to try it out.
I could disable virus protection maybe or build from source however it looks like they would stop making such harsh assumptions if the executable was signed according to:
https://www.symantec.com/connect/forums/how-avoid-wsreputation1-error

**Comment by vsavkin** [comment]
The executable is signed. If you right click on the exe file and click on properties, you should see "Digital Signatures" there. 

So I imagine it's a failing "reputation" check.

To fix it, we need to file an exception form. To do that we need: 
* Name of detection given by Symantec product
* The name of the Symantec product you use

Could you provide those?

**Comment by wiredprogrammer** [comment]
I'm getting this also.  The only information I can get from the history is the detection is named WS.Reputation.1 and the product is Norton Security Suite version 22.15.0.88.

**Comment by vsavkin** [comment]
@wiredprogrammer Thank you.

**Comment by vsavkin** [comment]
I filled an exception. I'm not sure how quickly they are going to process it thought.
