### ISSUE TITLE
Can't open directory drop down when attempting to import existing project (Windows 7)

### ISSUE THREAD

**Issue by asmith2306** [nrwl/angular-console#125]
Hi,

I get this error when attempting to open a directory when importing a project.

![image](https://user-images.githubusercontent.com/1416788/43970063-27c8dd46-9cc4-11e8-8385-d0b5195e3efc.png)

I've restarted the Angular Console a few times but no luck.  Error still present.

Thanks.

Edit: it's an issue with opening directories with a space in the name i.e. can't open any directories with this naming convention.

**Comment by vsavkin** [comment]
As far as I understand, this is due to Windows having synthetic directories for backwards compatibility that node doesn't handle. 

This is the fix: https://github.com/nrwl/angular-console/pull/183
