### ISSUE TITLE
[Feature Request] Allow opening project in terminal

### ISSUE THREAD

**Issue by beeman** [nrwl/angular-console#128]
It would be great if there was a way to open a terminal in the project dir, similar to the other apps in the header. 

![image](https://user-images.githubusercontent.com/36491/43973473-eeae1bac-9cd7-11e8-93b4-dd9a98eb842f.png)

**Comment by stefanoslig** [comment]
duplicate of #138

**Comment by beeman** [comment]
Well technically #138 is a dupe of #128 ;-) but one issue for adding a Terminal is indeed enough.
