### ISSUE TITLE
open in Webstorm button

### ISSUE THREAD

**Issue by michael-lang** [nrwl/angular-console#139]
This app is really cool, Thanks!

The video shows the Angular Console with a webstorm icon next to the VSCode icon.  I have both IDEs installed, but I only see the open in VSCode icon, and not one to open it in Webstorm.

I am running the app on windows 10, while the Video appears to be running on a Mac.  Should "open in Webstorm" be an option on the toolbar when "open in VSCode" is present?

How does an IDE get its icon on that toolbar?

**Comment by Yonet** [comment]
@michael-lang are you using Webstorm Early Access by any chance. EAP version doesn't get recognized but I will add them for the next version.

**Comment by michael-lang** [comment]
Version info:

WebStorm 2018.2.1
Build #WS-182.3911.37, built on August 7, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by vsavkin** [comment]
Currently, we look for editors in the directories specified in the PATH env variable.

For instance, this is one of the values I have in PATH: `C:\Program Files\JetBrains\IntelliJ IDEA 2018.2\bin`. 

You may have to add the directory where WebStorm is installed to PATH.

Once you do it, you should be able to run `webstorm.exe` from the terminal.

**Comment by michael-lang** [comment]
This works, thanks.

added to path: C:\Program Files\JetBrains\WebStorm 2018.2.1\bin

I just need to remember to update this path every time webstorm updates.

**Comment by WLun001** [comment]
I have the same issue on Mac
where I run `which webstorm` on terminal, it shows
`/usr/local/bin/webstorm`
