### ISSUE TITLE
Linux ubuntu version

### ISSUE THREAD

**Issue by Subhojit1992** [nrwl/angular-console#141]
Release an linux version software for the angular console. That will awesome. Because lots of developer used ubuntu

**Comment by calcerrada** [comment]
or Fedora...

**Comment by rodrigorhas** [comment]
Take a look at #101

**Comment by cvgaviao** [comment]
@Yonet, you have added the `duplicate tag` to this issue, but you have closed the #101 instead.  ;)

**Comment by vsavkin** [comment]
The 6.0.0.beta.2 release included a linux distribution. You can read more about it here: https://blog.nrwl.io/angular-console-6-beta-2-is-released-20c8e092e383.
