### ISSUE TITLE
Create new project/workspace with 3rd party Schematic 

### ISSUE THREAD

**Issue by martinmcwhorter** [nrwl/angular-console#142]
Currently when creating a new workspace AngularConsole only gives the choice of the default angular schematics or the nx schematics.

It would be beneficial to allow other, or internal, schematics to be used at this point.

**Comment by mrmeku** [comment]
I don't think we'll be able to support internal schematic sets (I would recommend using the CLI itself for that). But for public extensions I'm more than happy to add more! Are there any in particular you'd like to see added?

**Comment by martinmcwhorter** [comment]
Does the console extend the CLI directly?

All that would be needed would be yo allow appending a
--collection=someGlobalSchematic flag with ng new

**Comment by jaysoo** [comment]
Closing this since we've revamped Angular Console for vscode. We might look into create workspace again in the future so we can look into this at that time.
