### ISSUE TITLE
Creating application using @nrwl/schematic generates error "Cannot read property 'kind' of undefined" when using yarn

### ISSUE THREAD

**Issue by jerryorta-dev** [nrwl/angular-console#143]
# Steps to reproduce:

## 1. Create a workspace using @nrwl/shematics

![1-ac](https://user-images.githubusercontent.com/341155/43991683-d201e56e-9d37-11e8-9e28-4e342d8d3bf6.png)

## 2. Generate app using @nrwl/schematics  

Angular-Console generates this command line script:  
`ng generate application my-app --directory=my-app --viewEncapsulation=None --routing --prefix=my --style=scss --tags=ui`

![2-ac-generate-app](https://user-images.githubusercontent.com/341155/43991743-e7a5d00a-9d38-11e8-8a37-7bf31c5de87a.gif)

**Comment by jerryorta-dev** [comment]
This appears to be an `@angular/cli` issue

**Comment by cristianmartinez** [comment]
I got the same issue, even running the same command directly in the terminal.

 `ng generate application myapp`

**Comment by cristianmartinez** [comment]
These steps worked for me:

delete package_locked.json and node_modules folder
npm install again.

**Comment by jerryorta-dev** [comment]
@jsonberry confirmed my packageManager is set to yarn:

running `cat ~/.angular-config.json` yields

```json

{
  "version": 1,
  "cli": {
    "packageManager": "yarn"
  }
}
```

**Comment by Buttars** [comment]
This issue should be under the nw project. The issue is a conflict between yarn and the schematic, not angular-console.

**Comment by Buttars** [comment]
Looks like a possible typescript / tslint issue https://github.com/palantir/tslint/issues/3689

**Comment by Yonet** [comment]
Fixed: https://github.com/nrwl/angular-console/pull/176
