### ISSUE TITLE
dry run flag option

### ISSUE THREAD

**Issue by abannsunny** [nrwl/angular-console#146]
Hi 
First of all I love the tool!
An option to do a dry run when running the generate commands will be very helpful.

Thank you.

**Comment by stefanoslig** [comment]
I'm not sure if this option will be useful, if you think that every time you change an option, the new command runs in --dry-run mode in order to give you feedback about the output. The tool runs your command in --dry-run mode after any change by default.

**Comment by Yonet** [comment]
@abannsunny closing the issue. Thanks.
