### ISSUE TITLE
Unable to generate NgRx Schematics

### ISSUE THREAD

**Issue by jsonberry** [nrwl/angular-console#147]
## Versions
`@angular/cli`: ~6.1.0
`@nrwl/schematics`: ~6.2.0

## Steps to reproduce

1. Generate new project with @nrwl/schematics
1. Generate lib `foo`
1. Attempt to scaffold NgRx state module tied `foo` module

## Expected
NgRx module scaffold done in `foo` lib

## Actual
Error is thrown: `Path does not exist: foo.module.ts`

**Comment by Yonet** [comment]
@jsonberry the workaround is to write the whole path manually. 

Ex: instead of foo.module, libs/foo/src/lib/foo.module.ts  

Error happens because of autocompletion. 

Duplicate: https://github.com/nrwl/angular-console/issues/91

**Comment by jsonberry** [comment]
@Yonet ah thanks! I had tried the full path earlier but it didn't work, I must have missed part of the path because I just tried it again and the workaround of entering the full path *does* work correctly.

Thanks!

**Comment by chauey** [comment]
Can highlight and copy from the dropdown option (before releasing the mouse buttton)
