### ISSUE TITLE
feat: Add ability to choose path when adding a new component etc.

### ISSUE THREAD

**Issue by samedwards1989** [nrwl/angular-console#150]
When adding a new component or any of the options on the 'Generate Code' section, it would be good if you could set the directory where you would like it to be created instead of just creating them in the default `src/app` directory.

E.g

I want a create-user component to be created in `src/app/user-list` directory

**Comment by stefanoslig** [comment]
You are able to select the module where your component will be created. So if you have a user-list.module.ts under src/app/user-list, then what you want to do is to select the appropriate module. See the bellow picture:
![image](https://user-images.githubusercontent.com/6942946/44030047-3bd25470-9f08-11e8-8448-481eda092330.png)

If you don't have a module under src/app/user-list and you want to create a component under this folder then you should add the folder's name(path) in the name of your component. See the below picture:
![image](https://user-images.githubusercontent.com/6942946/44030295-117be14a-9f09-11e8-9c2e-f13da1ead8ae.png)

**Comment by samedwards1989** [comment]
@stefanoslig Okay thanks for that, maybe a tree view to select the folder you want so you dont have to keep typing it in if you have multiple components to add would be a good idea

**Comment by dungahk** [comment]
I agree with @samedwards1989 here, the idea behind Angular Console is to make it easier for people that have never used ng-cli before, those people wouldn't know they can do what @stefanoslig mentioned. Even though I think people should always choose a module for a component, it is not a required option.

A file tree would be a good approach for this.

**Comment by mrmeku** [comment]
We won't be able to fix this unless the underlying schema is changed to allow us to specify a directory via a flag. Would you mind re-filing your issue here?  https://github.com/angular/angular/issues

Once there is a corresponding flag, I think implementing a directory picker for that flag is definitely something I'd like to do. If and when that flag gets added, I'll re-open the issue

**Comment by dungahk** [comment]
Don't you think https://github.com/angular/angular-cli would be a better fit?

**Comment by cm0s** [comment]
I think this feature is a must have to improve productivity. On complex application, you can have nested structure of folders which makes "typing the folder path every time you want to generate a component" a bit tedious.

From the angular-cli point of view, the ng generate command takes into account the folder from where you run the command.

When typing : 
`~/my-project/src/app/home/$ ng g c my-component`
my-component is created in the home folder and not in the app folder.

Could it possible for Angular Console to make a `"cd"` in the right folder before running the`ng generate` command (making the use of an angular-cli flag not necessary)? By `cd`, I mean moving to the right folder or just running the command from within the folder selected by the user.

When you are inside a terminal it's still OK to navigate through folders using the `cd` command. Thanks to autocompletion and `ls` you can navigate quickly, but on the Angular console in the component name input you don't have autocompletion and `ls` command. You have to be sure about the folder path you type before generating the code.

**Comment by samedwards1989** [comment]
> We won't be able to fix this unless the underlying schema is changed to allow us to specify a directory via a flag. Would you mind re-filing your issue here? https://github.com/angular/angular/issues
> 
> Once there is a corresponding flag, I think implementing a directory picker for that flag is definitely something I'd like to do. If and when that flag gets added, I'll re-open the issue

Could you not just run the `cd` command first to navigate into that directory then run the `ng generate c` command?
