### ISSUE TITLE
Show Visual Studio Code - Insiders edition in console

### ISSUE THREAD

**Issue by johnpapa** [nrwl/angular-console#151]
VS Code shows up nicely, but a lot of folks use Code Insiders edition exclusively.

It would be awesome to detect that and show it in the console.

In the future, it would be nice to have a settings view where we can hide or show some of these detected applications, too. That way if there are a lot of them we can focus on the ones we want most.

![image](https://user-images.githubusercontent.com/1202528/44035498-a9b45db0-9edd-11e8-8e74-56f66394d3bf.png)

**Comment by Yonet** [comment]
Related to https://github.com/nrwl/angular-console/issues/139

**Comment by TekSiDoT** [comment]
Is this issue open for a PR?

**Comment by mrmeku** [comment]
This feature was added via commit 88d0dd6920a6b1e6cd47e200e501c8f9fc336af5
