### ISSUE TITLE
Opened a 2nd Angular Console window and nothing is listed in Recent

### ISSUE THREAD

**Issue by chauey** [nrwl/angular-console#153]
I tried reloading.  Am on Windows 10.

**Comment by stefanoslig** [comment]
Yes, that's true. The problem is that the second window opens in a different random port (not in 7777) so the localStorage where your recent projects have been saved is empty. In my opinion this is not exactly an issue. It's a normal behavior.

**Comment by chauey** [comment]
Thx for the info and enlightenment. I found it confusing and felt it was broken, and did not want to use the 2nd window; so I think others may also. Either make it work the same and pull the same data or prevent from opening more than 1 for now?

**Comment by Yonet** [comment]
Related to https://github.com/nrwl/angular-console/issues/133

**Comment by Yonet** [comment]
@chauey this behavior will be solved with this issue: https://github.com/nrwl/angular-console/issues/133. Closing this one. Thanks.
