### ISSUE TITLE
Show ngrx schematics in generate code tab

### ISSUE THREAD

**Issue by Reaver86** [nrwl/angular-console#154]
Our nx project only shows the nx schematics and the angular schematics. It would be great if angular console would realize we imported @ngrx/schematics and also show those in the generate code tab.

**Comment by Yonet** [comment]
Related to https://github.com/nrwl/angular-console/issues/96

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/angular-console/commit/1b98dd9feb91679c0339b237896d6764ee8dae89

Thank you!
