### ISSUE TITLE
Feature idea: Buttons on the start site should use npm run if existing

### ISSUE THREAD

**Issue by chaosmonster** [nrwl/angular-console#157]
Feature idea

The quick buttons on the start site next to the project/libraries and application should use the `npm run "name"` if it exists in the `package.json`.

example

**package.json**
```
scripts:{
  build: "ng build -c=stage"
}
```
so `npm run build` will work, but `npm run test` would throw an error in this example, as it does not exist.

The buttons should use `npm run build` for the build button and `ng test` for the test button

**Comment by chaosmonster** [comment]
If you support this idea I would create a pull request with an implementation.

**Comment by vsavkin** [comment]
@chaosmonster It's a good idea for workspaces with a single project, but it wont' work once you have more than one project you can build, which CLI6 supports. We won't be able to tell which build script is supposed to build which project.  Does it make sense?

We are in the process of rethinking the projects screen to incorporate use cases like that.

**Comment by chaosmonster** [comment]
That is a good point didn't think about it. For the sake of creative thinking, would it be an idea that the above feature is used for the "default" (as configured in the angular.json) project and every other project needs to be prefixed like `anotherApp:build`?

**Comment by mrmeku** [comment]
@chaosmonster Ultimately we are going to be replacing the quick action button on the overview screen with a very different UI than what you see now. I'm going to close this issue for now, but know that I'm definitely thinking about ways to pin actions a particular workplace/project usually runs as we design the updated UI
