### ISSUE TITLE
(Bug) - unable to create project even though all required fields are populated

### ISSUE THREAD

**Issue by ndcunningham** [nrwl/angular-console#160]
My current setup is a windows 10 64bit Desktop Machine using the Angular Console.

The problem i am experiencing is that I am unable to create a project after previously cancelling.

Step 1. Start Angular Console 
Step 2. Navigate to Create
Step 3. Select a parent Directory
Step 4. Name your workspace
Step 5. Select any schematic
Step 6. Click Create
Step 7. Click Cancel
Step 8. Repeat Steps 3 - 5.

Issue: You will see that the create button is not enabled. 

![image](https://user-images.githubusercontent.com/338948/44180250-5f260d00-a0c9-11e8-99d4-e5899b41053d.png)

I figured out that if you *must* click cancel twice in order for the create button to be enabled.

I don't think it is expected to behave this way.

**Comment by Yonet** [comment]
@ndcunningham I am not sure why you need to press cancel. Are you seeing the terminal window that logs the created files after step-3?

**Comment by ndcunningham** [comment]
@Yonet Here is the scneario:
On the first pass (Step 1 - 6) everything works as expected but i made a mistake with the name of my project. 
So i click on the cancel button to re-enter the That i want name.

After re-entering all the details i need i am still unable to click create. I must click cancel one more time then click create.

The second time i click on cancel, the create button is the only button available.
What i am asking is that the first time i click on cancel the create button should be enabled once i enter all my details.

**Comment by mrmeku** [comment]
I think this should be fixed now. If its not please reopen the issue
