### ISSUE TITLE
Create A New Workspace

### ISSUE THREAD

**Issue by oleksiipotiekhin** [nrwl/angular-console#163]
There is no possibility to add params when you are creating a new application. For example `--style scss` or `--routing`.

![image](https://user-images.githubusercontent.com/30025319/44195051-312be180-a138-11e8-894e-04e1f1f09a95.png)

**Comment by mrmeku** [comment]
I'm going to be redoing this UI soon and I'm going to make sure that this issue is addressed when I do. Thanks so much for filing the issue
