### ISSUE TITLE
[enhancement] Watch notifications

### ISSUE THREAD

**Issue by drewpayment** [nrwl/angular-console#164]
I am thoroughly enjoying the functionality, but when I turn a watch on and the application gets buried I have no idea if I'm watch has finished rebuilding. 

It might be convenient to be able to enable a desktop notification to show a flag or even flash the icon when the rebuild has start/finished?

**Comment by mrmeku** [comment]
This is a great idea.

**Comment by manekinekko** [comment]
I'm working on this one.

**Comment by jaysoo** [comment]
Closing this since there hasn't been any movement, and we've also revamped the vscode experience.
