### ISSUE TITLE
Add Clarity Schematic

### ISSUE THREAD

**Issue by technbuzz** [nrwl/angular-console#168]
The [Clarity Design System](https://vmware.github.io/clarity/documentation/v0.12/get-started) from VMware  comes with Good angular components and they did great work on UX guidelines as well.

They do support `ng add` command I think it should be added to Extension/Schematics List.

**Comment by TekSiDoT** [comment]
Looks like @clr/angular is [already available in the extension list.](https://github.com/nrwl/angular-console/blob/d89c1a8b74be5345a71dd8fd42b4e1ef62ca76d5/server/src/read-extensions.ts#L29)

**Comment by technbuzz** [comment]
Hmm it was already there but with a typo. That's why I couldn't search it.

![image](https://user-images.githubusercontent.com/1523391/44527331-8a2ae500-a6f7-11e8-844a-de81e91e8f19.png)

**Comment by TekSiDoT** [comment]
Yeah I saw that too, funnily enough it's correctly described [in the actual code](https://github.com/nrwl/angular-console/blob/d89c1a8b74be5345a71dd8fd42b4e1ef62ca76d5/server/src/read-extensions.ts#L29), looks like some auto replacement bug?

**Comment by vsavkin** [comment]
My fault. I was rushing a bit before the release.

It has been fixed here: https://github.com/nrwl/angular-console/commit/d89c1a8b74be5345a71dd8fd42b4e1ef62ca76d5. We will cut another release with this fix soon.
