### ISSUE TITLE
App Shell task incorrectly attempts to run as `ng app-shell [app-name]`

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/angular-console#169]
Running an app-shell task attempts to run as `ng app-shell [app-name]`; however, [it is intended to run](https://github.com/angular/angular-cli/wiki/stories-app-shell) as `ng run [app-name]:app-shell`.

Angular Console seems to be assuming all architect tasks will follow the `ng [task-name]` format, which is perhaps normally the case; however, in the case of App Shell and perhaps in other Architect implementations in the future might not be so.

<img width="598" alt="screenshot 2018-08-19 17 49 22" src="https://user-images.githubusercontent.com/9163179/44315447-09a77400-a3d9-11e8-8492-ab05680fed88.png">

**Comment by mrmeku** [comment]
@vsavkin It looks like that particular schematic isn't publishing any metadata we can use to understand that there is a positional argument which precedes `:app-shell` (https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/app-shell/schema.json#L10). We'll either have to special case this particular schematic or file a bug against angular_devkit

**Comment by mrmeku** [comment]
I'm not sure if this is an issue anymore so I'm closing it for now
