### ISSUE TITLE
apps still visible in console

### ISSUE THREAD

**Issue by kauteetech** [nrwl/angular-console#170]
I created sample apps, i deleted them from the explorer, but the apps are still visible in the console.
is there a way to delete them

**Comment by stefanoslig** [comment]
This is because angular-console observes the angular.json file and your sample apps are still there.

**Comment by Yonet** [comment]
@kauteetech you also need to delete them from nx.json. Closing this issue, feel free to open again if you still have the issue after you delete the app from angular.json and nx.json. Thanks!
