### ISSUE TITLE
Add ngrx store-development tools to add/remove cli extensions

### ISSUE THREAD

**Issue by LloydTDavies** [nrwl/angular-console#172]
Would it be possible to add ngrx store-development into the add/remove extensions?
If possible with the import into app.module.ts with the only import if environment is not production.

**Comment by Yonet** [comment]
@LloydTDavies if you use the nx schematics ngrx, the ngrx store dev tools are set automatically. You can see what nx schematics adds in this diff: https://github.com/nrwl/nx-examples/commit/fdfabfd5cee547c4d583d7e64d255cf0996c8983.
We can not add that functionality to the ngrx schematics directly but you can ask for it on ngrx repo. Closing the issue.
