### ISSUE TITLE
Bug: Cannot return null for non-nullable field Workspace.name.

### ISSUE THREAD

**Issue by bgotink** [nrwl/angular-console#177]
When importing an existing angular-cli application, I get a toast saying

```
Cannot return null for non-nullable field Workspace.name.
```

and nothing happens.

**Comment by vsavkin** [comment]
@bgotink we read the name property from package.json. Do you have it blank there?

**Comment by bgotink** [comment]
Oh yeah, that's empty. I was looking all over the `angular.json` for a name, but simply didn't think of the `package.json`&hellip; A different error message could really help here, but apart from that this issue can be closed for me 😄

**Comment by mrmeku** [comment]
Sounds like we just need to catch the error in question and produce a clear error message before we close this one out.
