### ISSUE TITLE
Page: subscribe button not working

### ISSUE THREAD

**Issue by carrbrpoa** [nrwl/angular-console#178]
**Subscribe to Angular Console updates** button not working in https://angularconsole.com.

**Comment by vsavkin** [comment]
@carrbrpoa the subscribe button open a popup? Maybe the browser is blocking it for you?

**Comment by carrbrpoa** [comment]
I don't think so. I see error in console for each click in the button:
![image](https://user-images.githubusercontent.com/10212618/44739180-7a334c80-aacd-11e8-94e7-017dca10a5fa.png)

**Comment by ndcunningham** [comment]
What version of chrome are you running?
I tried and it works

**Comment by vsavkin** [comment]
@carrbrpoa I think this might be due to a temp issue with mailchimp. Can you try it again?

**Comment by vsavkin** [comment]
Closing this issue. Could you reopen it if the issue persists?

Thanks!

**Comment by carrbrpoa** [comment]
It's working now!
