### ISSUE TITLE
@angular/material schematics not availabe in imported project

### ISSUE THREAD

**Issue by Dgiulian** [nrwl/angular-console#182]
After importing a previously generated project to Angular Console that had the @angular/material schematics already added, the console displays that the package is already installed, but the schematics aren't available in the generate code section. Only @angular/schematics code is available.

Angular Version: 6.0.0
@angular/material: "^6.2.1"

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/angular-console/commit/1b98dd9feb91679c0339b237896d6764ee8dae89

Thank you!
