### ISSUE TITLE
Feature: Update Angular Console through the application

### ISSUE THREAD

**Issue by ndcunningham** [nrwl/angular-console#193]
It would be really convenient if we could update the angular without going to the website to download it.

Possibly through a notification:
1. when the application is launched it could check to see if there is a new version
2. if there is a new version show a message about the new version
3. user has the opportunity to click the message which would download > unwrap and execute 
4. relaunch the application

**Comment by vsavkin** [comment]
@ndcunningham the application already does the 4 steps. It checks if there is a new version, downloads it, and then installs it. Are you on Win or Mac?

**Comment by vsavkin** [comment]
@ndcunningham 

Thank you for filling the issue. 

This is what happened. We had autoupdating setup from Day 1, but we had an issue with the beta2 windows binary. The binary got renamed and that broke the auto updating. 

I fixed the existing beta2 release, and also updated our build process not to have such issues in the future (see here: https://github.com/nrwl/angular-console/commit/eeb5404c242bce4f740249f8c60ff1623c960e35).
