### ISSUE TITLE
windows download url link is broken

### ISSUE THREAD

**Issue by jeffkenz89** [nrwl/angular-console#194]
cannot download from this link https://github.com/nrwl/angular-console/releases/download/v6.0.0-beta.2/AngularConsole-Setup-6.0.0-beta.2.exe.

**Comment by rafaellyra** [comment]
This is the correct one https://github.com/nrwl/angular-console/releases/download/v6.0.0-beta.2/Angular.Console.Setup.6.0.0-beta.2.exe
