### ISSUE TITLE
Discrepancy with source map 

### ISSUE THREAD

**Issue by nathanvv** [nrwl/angular-console#196]
I had angular cli 6.2.1 globally installed.
I installed the "Angular.Console.Setup.6.0.0-beta.2.exe" binary for windows.

Using console : ng build --help
The cli says that "--source-map" is the option to output source map
![image](https://user-images.githubusercontent.com/11080029/45265805-9c569400-b416-11e8-9b2b-254e9e665933.png)

Noticed that the UI provides the "sourceMap" option to enable/disable it. The default seems to be true, however when turning it off adds a "--no-sourceMap" and turning it back removes the "--no-sourceMap" option.

![image](https://user-images.githubusercontent.com/11080029/45265834-f0617880-b416-11e8-912c-846ed63ce96f.png)

I get that the param changed with the recent angular cli release. 

So does the ui install its own corresponding version of the angular-cli, or does it use the pre-installed global angular cli version ?. Does the UI display the version of angular cli that its referencing ?.

**Comment by vsavkin** [comment]
The ui works like this:

1. It uses its own version of the CLI to create new projects.
2. It uses the version of the CLI your project uses to run commands within your project. 

So `ng build` will run ng from './node_modules/.bi/ng`.

Could you check if `ng build --help` and `./node_modules/.bin/ng build --help` return the same information?

I also think it's a good idea to show the version of the CLI used.

**Comment by mrmeku** [comment]
This should be fixed in our latest release
