### ISSUE TITLE
Missing RAM disk and RAID Disk

### ISSUE THREAD

**Issue by qq6techsupport** [nrwl/angular-console#198]
On my computer the RAM disk U: and RAID disk Z: both missing. 
(refer to the following screenshot.)
![image](https://user-images.githubusercontent.com/15965698/45271266-464a2500-b4d8-11e8-90ef-65b9ca1508a3.png)

**Comment by mrmeku** [comment]
This is likely a permissions error that we get with our current implementation of how we scan for directories. When we switch to a native file picker (tracked in #237) This should be fixed (assuming Angular console has permissions to write to those disks of course)
