### ISSUE TITLE
got this json error when to try open my project

### ISSUE THREAD

**Issue by jeffkenz89** [nrwl/angular-console#202]
at 1st i can open but  after sometime i can't open project in angular console again, this is the message 
i got when try to open project 
![image](https://user-images.githubusercontent.com/21219550/45594397-3e9ceb80-b9c4-11e8-824f-5fc75bdc92f0.png)

**Comment by vsavkin** [comment]
@jeffkenz89 Unfortunately, we don't display the file name that cause the parsed error. Given what you described, it's either angular.json or package.json. Could you check position 2928 in both the files?

**Comment by jeffkenz89** [comment]
> 
> 
> @jeffkenz89 Unfortunately, we don't display the file name that cause the parsed error. Given what you described, it's either angular.json or package.json. Could you check position 2928 in both the files?

after generate lib from cmd it's fix automatically,my angular json & package json  has no problem
