### ISSUE TITLE
scripts section is missing from package.json

### ISSUE THREAD

**Issue by chgc** [nrwl/angular-console#203]
Compare project created by Angular Console and Angular CLI. I found that scripts section is missing if the project is created by Angular Console. It seems the `@schematics/angular` that include in Angular Console is different than Github version.

![image](https://user-images.githubusercontent.com/4550568/45606038-6c416d80-ba74-11e8-86e4-a245b41a4399.png)

**Comment by mbaljeetsingh** [comment]
I was about to create an issue about that too.
