### ISSUE TITLE
Allow for specifications of dir when generating service

### ISSUE THREAD

**Issue by mackelito** [nrwl/angular-console#205]
when generating a service it ends up in the src/app/ dir (or src/app/[service.name]/.. would be nice to be able to specify a path

**Comment by vsavkin** [comment]
Angular Console only support the options supported by the Angular CLI. 

Run  `ng g service --help` within your project to see what options the used version of the CLI supports. 

I see something like this:

```
  --dryRun (-d)
    Run through without making any changes.
  --flat
    Flag to indicate if a dir is created.
  --force (-f)
    Forces overwriting of files.
  --project
    The name of the project.
  --spec
    Specifies if a spec file is generated.
```

Once the CLI the path option, angular console will start supporting it automatically.

Let me know if it makes sense.

**Comment by mackelito** [comment]
😳I actually thought that it already did!... sorry, my bad!
