### ISSUE TITLE
After executing a task from the projects overview, I end up in the task view

### ISSUE THREAD

**Issue by mslourens** [nrwl/angular-console#208]
Steps to reproduce:

- Click test on the projects overview
- After the tests are done, click the Cancel button
--> You are navigated back to the Tasks overview, instead of the projects overview.

Expected behavior: When I press cancel, I expect to go back where I came from, whether it is the Projects overview or the Tasks overview.

**Comment by mrmeku** [comment]
Eventually, when I introduce a more desktop friendly layout, this behavior will be desirable. With that in mind I'm going to leave it as is as I work towards making the UI a reality
