### ISSUE TITLE
It is not clear how to go back to the home screen

### ISSUE THREAD

**Issue by mslourens** [nrwl/angular-console#209]
There is no clear way how I can open another project. I expect the open button in the projects overview to allow me to open another project. Instead it opens the project either in the explorer or in VSCode. It took me a while to figure out I had to click on the logo to go back to the home screen. 
Where this is normal behavior on a website, I don't expect this in an application. I suggest to add a Home button. 

After I navigated to the home page, there is no way to go back to my project, other than going to the Recent projects tab and open my previous project again. This is also not very intuitive.

**Comment by mrmeku** [comment]
We've tweaked this UI element now
