### ISSUE TITLE
Change import tab to Open

### ISSUE THREAD

**Issue by mslourens** [nrwl/angular-console#210]
When clicking on import, you actually don't move any code around, so the project is not imported, you just read the angular.json file and add the possibility to run tasks from the package.json file. I would suggest to change the name Import to Open, which is more in line with what you do on that tab.

**Comment by vsavkin** [comment]
@mrmeku what do you think? "Open" makes sense to me.

**Comment by jaysoo** [comment]
Additional wording changes here #236.
