### ISSUE TITLE
Feature request: manage open in external application list

### ISSUE THREAD

**Issue by mslourens** [nrwl/angular-console#211]
Currently when I click the open button, I am greeted with two options: Open in Explorer and Open in VSCode (on Windows). I would like to be able to manage these options: add another for Webstorm and get rid of VSCode for example.

**Comment by vsavkin** [comment]
@mslourens we don't allow you to edit those, but you should be able to see webstorm. Are you using WebStorm EAP?

**Comment by mslourens** [comment]
No, I'm using Webstorm 2018.2.3 (on Linux Mint)

**Comment by vsavkin** [comment]
@mslourens you have to add the webstorm to the PATH env variable (for instance, I have my idea added to path: `C:\Program Files\JetBrains\IntelliJ IDEA 2018.2\bin`)

**Comment by mslourens** [comment]
I'm also running Linux Mint, and when I add the webstorm bin folder to my path, I can open Webstorm with the terminal, but it doesn't show up in the open list.

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
