### ISSUE TITLE
The app is missing an icon on Linux

### ISSUE THREAD

**Issue by mslourens** [nrwl/angular-console#212]
When installing Angular Console on Linux (Mint), there is no icon associated with the app, neither in the menu nor in the quick switch (ALT + TAB):
![angular-console-icon](https://user-images.githubusercontent.com/1907152/45816405-d3149000-bcdb-11e8-8b30-5cf2d0a87a1c.png)

**Comment by mrmeku** [comment]
Will be fixed by our next release :)

**Comment by tayambamwanza** [comment]
@mslourens  is this fixed for you? I'm still having this issue on v8. I'm on linux mint

**Comment by mslourens** [comment]
@tayambamwanza for me this issue is not fixed, I still don't see an icon in my Mint menu.

**Comment by tayambamwanza** [comment]
@mrmeku still not working, not sure what info we can provide to help with fix? Maybe it's a caching issue? I kind of just tolerated it but it's annoying having a blank space in the app tray.

**Comment by tayambamwanza** [comment]
@mrmeku @vsavkin VS Code recently had an update that included a change to their app icon. My icon didn't change but in the changelog they gave a suggestion to fix the problem.

I eventually found a suggestion for linux, they asked to run `sudo update-icon-caches /usr/share/icons/*`

After running that command restarting the PC would cause the icons to refresh, my vs code icon updated  to the new one, angular console still has an invisible icon :|

[vs code linux icon fix](https://github.com/microsoft/vscode/issues/71827#issuecomment-499224055)

**Comment by tayambamwanza** [comment]
I did a search on that path for angular console and only got one result in the hicolor folder.

When I search for vs code icon "code.png" it appears in multiple folders "mint-x" "mint-y" "paper"

**Comment by tayambamwanza** [comment]
@mrmeku @vsavkin I seem to have found a workaround, It's an electron issue apparently.

I found the icon in the hicolor folder under the additional folder 0x0 which I thought was a funny name for an image size, so I googled further and found this.

https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-377562602
