### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by MichaelWarneke** [nrwl/angular-console#214]
Wondering if windows subsystem for linux (WSL) will be supported and when?

**Comment by vsavkin** [comment]
It's on the roadmap. We are planning to add support for WSL in Q4 2018.

**Comment by mrmeku** [comment]
@MichaelWarneke It looks like rendering Angular Console using WSL would be awefully tricky since its not on Microsoft's priority list to help with getting xserver up and running (see https://github.com/Microsoft/WSL/issues/2356). Unless I'm completely off base (in which case please reply and tell me so) I think we won't be able to implement this feature

**Comment by sarunint** [comment]
Yes @mrmeku, you are completely off-base.

What I think @MichaelWarneke wanted is a Windows version of Angular Console, but calls `ng` installed in WSL. Kinda like WSL console in VSCode.

**Comment by MichaelWarneke** [comment]
> 
> 
> Yes @mrmeku, you are completely off-base.
> 
> What I think @MichaelWarneke wanted is a Windows version of Angular Console, but calls `ng` installed in WSL. Kinda like WSL console in VSCode.

That's correct. Would be nice if the user can choose the bash to be used (e.g wsl bash).

**Comment by vsavkin** [comment]
Folks. This is part of the bigger feature:

The user should be able to configure how commands actually run. On windows the three popular options are:  wsl bash, powershell, cmd. But a similar capability must be provided on other platforms as well.

**Comment by the-ult** [comment]
Will this feature be available in the VSCode plugin anytime soon?

Love the work you guys are doing!

**Comment by MichaelWarneke** [comment]
Just found this project running the cli commands in the integrated terminal which can be any terminal.
https://github.com/ultrasonicsoft/ng-cli-vsx
It doesn't look very complicated to run the commands in that terminal.
Could this work with the Angular Console VS Code extension?

**Comment by mrmeku** [comment]
We added this to vscode in our latest release! Enjoy everyone :)

**Comment by myflowpl** [comment]
Any info how to configure or change settings to enable angular console to work with WSL bash ??
I have v 7.4.5 and no idea how to run it 
I have no node installed on my windows, only WSL where the node is available

**Comment by Empereol** [comment]
@myflowpl 

Initially when prompted that you are missing Node.js, just select that you will install it manually... Then you are able to access the settings where you can toggle "Use WSL". After that it should work correctly without needing Node installed in Windows.

![image](https://user-images.githubusercontent.com/746530/57247901-0c053900-700f-11e9-81a6-6198d176ed14.png)

**Comment by myflowpl** [comment]
@Empereol Thanks a lot, now it works and it's so awesome.

I just didn't notice the " install it manually" button and couldn't reveal the settings panel.

**Comment by michahell** [comment]
This is still unsolved... how do we change the default terminal to the one NX console needs to target? this is as of yet completely unclear to me... my default terminal in vscode is setup to use what I want, which is ZSH 🤷‍♂️ but NX console seems to ignore this and try to run commands in the awful CMD shell.

**Comment by alienfacepalm** [comment]
I had it working great with WSL, use WSL bash to run `code .` in my project, which pops open the VSCode using remote to the WSL instance, Nx Console commands were run in zsh as I had configured it. Now, something change, no idea what and it says it can't find wsl.exe anymore. It's trying to use wsl.exe, and the file is there, but Nx Console can't see the darned thing. What gives?

**Comment by saitodisse** [comment]
> This is still unsolved... how do we change the default terminal to the one NX console needs to target? this is as of yet completely unclear to me... my default terminal in vscode is setup to use what I want, which is ZSH 🤷‍♂️ but NX console seems to ignore this and try to run commands in the awful CMD shell.

I'm using zsh too, getting this error at Nx Console OUTPUT:

```
Nx Console encountered an error when activating
{}
TypeError: Cannot read property 'getWorkspacePath' of undefined
```

I have tried turn on WSL option but the error remains.
![image](https://user-images.githubusercontent.com/155953/146969122-18fa115a-4c69-44bd-8ec9-aa1055b5d97e.png)

**Comment by alienfacepalm** [comment]
Open your WSL terminal type ```$ code .``` It'll launch VSCode in Remote mode
