### ISSUE TITLE
Feat - About / Version window

### ISSUE THREAD

**Issue by ndcunningham** [nrwl/angular-console#215]
It would be great if we got a window that tells what version of the Angular Console which we currently have installed.

1. Launch the Angular Console
2. Either we have the version maybe at the footer or available through a menu item.
3. If it's a user menu item when it's clicked a dialog / window displays which has the version.

**Comment by vsavkin** [comment]
@ndcunningham this is a good idea, and we already have it working on a mac. Would you like to send a PR that adds similar functionality for the windows build?

**Comment by ndcunningham** [comment]
@vsavkin Sure will do

**Comment by ndcunningham** [comment]
@vsavkin i could use some help with this i can't seem to find where the event is fired when a menu option is clicked. 
I can see a `invoke` method is called from: https://github.com/nrwl/angular-console/blob/master/libs/ui/src/lib/contextual-action-bar/contextual-action-bar.component.html#L24

I assume that the values are retrieved from the appollo server database?

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
