### ISSUE TITLE
Open workspace which is inside another workspace

### ISSUE THREAD

**Issue by sirajc** [nrwl/angular-console#222]
We have our library setup as Angular CLI workspace, inside that we have a folder which has seperate Nx workspace that has our application that uses the parent library.
Import option shows parent CLI workspace, but there is no way to expand that folder and import the Nx workspace that is inside CLI workspace. Scan and List them or provide option to expand the parent folder.

Here is the structure
```
/my-library
    angular.json
    my-styleguide
         angular.json
         nx.json
```

In the example above, I can import my-library in AngularConsole but not my-styleguide

**Comment by mrmeku** [comment]
#237 Will fix this
