### ISSUE TITLE
PKGBUILD for angular-console

### ISSUE THREAD

**Issue by Buttars** [nrwl/angular-console#226]
Hi guys!

I'm putting together a PKGBUILD for Angular Console so our Arch Linux friends can easily download the app from the AUR.

What commands do I need to run in what order?

After running

```
yarn
yarn start dev.prepare
yarn start linux.builder-dist
mkdir osbuilds
yarn start linux.copy-to-osbuilds
```
I manually unpack the files and attempt to do ./angularconsole which responds with `Error when starting Angular Console: Cannot find module 'dotenv'`

I've been trying for a while to get this working but have exhausted my options with my limited knowledge about the project.

:smile:

**Comment by jeffbcross** [comment]
This was an error that has since been fixed. Can you try again with master?

**Comment by Buttars** [comment]
Hi Jeff,

I'll give it a go again here soon and report back!

**Comment by Buttars** [comment]
Works beautifully. I'll be pushing a package to the AUR. 

Thanks!
