### ISSUE TITLE
Feature -   starting directory = creation directory -  Linux

### ISSUE THREAD

**Issue by waratah** [nrwl/angular-console#233]
When I run angular console and click create in xubuntu it starts from the root directory.  Not the current directory where it was started nor the one last referenced in the previous session.

If I start angular console in the current directory it should start from there.  Even if adding a '.' to say start here.

Might be good for it to check for a project in the current directory and automatically add it if it is an angular 6.

NB:  there is no -h or -v option.

**Comment by wernert** [comment]
Hello
I have installed the console 7.4.3 on xubuntu 18 with node 10.15.3 via deb download.
Then started the app via terminal $angular-console_ in a folder. 
Open or create new Workspace has the current folder path in the opening file browser.
If the the app is started from start menu : folder paths are the home folder of the user.

So I would like to ask: is this issue resolved or do I miss something ?

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
