### ISSUE TITLE
Use native file dialog

### ISSUE THREAD

**Issue by jaysoo** [nrwl/angular-console#237]
Since users are used to using their system's native file dialog, we should leverage this in the console. We would also benefit from native features such as folder creation, keyboard shortcuts, and remembering the last folder used.

## Affect workflows

This applies to the Create and Open workflows, and any future usages of file picker.

## Additional notes

For the Open workspace case, this will likely mean that we need to perform validation against CLI 6+ *after* the workspace is selected as we will not be able to prevent user from selecting any ordinary directory.

**Comment by mrmeku** [comment]
As noted in #195 we should probably default this directory to either their last used directory or their home directory. Either way, something closer to where their project is most likely to be located

**Comment by mrmeku** [comment]
In progress over at: https://github.com/mrmeku/angular-console/tree/native_file_picker

**Comment by mrmeku** [comment]
Fixed via #278
