### ISSUE TITLE
Creating an application with routing flag ON showing an error.

### ISSUE THREAD

**Issue by jafsparrow** [nrwl/angular-console#260]
![angular console error](https://user-images.githubusercontent.com/20259431/46900874-3e124a80-cec7-11e8-8ec9-b3494a78748f.PNG)

if I take out --routing from it (by unfalgging it on angular console), it works and shows the --dry-run results.

I think this is happening with the new update on 12 Oct 2018

**Comment by jafsparrow** [comment]
when I unflagged 'skipTests', it worked fine. Not sure if its with --routing flag or --skiptest flag.

**Comment by mrmeku** [comment]
@jafsparrow Can you log this bug over at https://github.com/nrwl/nx/issues and provide the version of @nrwl/schematics in your workspaces package.json? This is an issue with the schematics rather than console
