### ISSUE TITLE
[enhancement] Show popular/preferred extensions first

### ISSUE THREAD

**Issue by johnpapa** [nrwl/angular-console#268]
create a sorting that shows the super popular extensions first. why? because this will grow and the ones like material should be up top for easier access.

**Comment by johnpapa** [comment]
Off the top of my head ...

1. begins with `angular/*`
2. X number of downloads or github stars (10k ?)  - something high - or maybe relative. Perhaps use a std dev with the top 5 from that.
3. Hand picked ones that are endorsed by the Angular team (always need exceptions)
4. User selected favorites - stored for a person, and shareable for a team

**Comment by jaysoo** [comment]
Closing this issue since we've revamped the Console extension for vscode, and this screen doesn't exist. We're considering adding support directly in Nx instead.
