### ISSUE TITLE
[enhancement] show installed extensions in a visual way

### ISSUE THREAD

**Issue by johnpapa** [nrwl/angular-console#270]
Currently, it is hard to tell which ones are installed or not at a glance (see below). I recommend allowing filtering of this, sorting (or grouping), and a visual icon so it's identifiable at a glance.

![image](https://user-images.githubusercontent.com/1202528/47114869-fa06a900-d22a-11e8-8afa-240eee2ef37a.png)

**Comment by georgewilde** [comment]
#447 adds "Installed" to the right side of the extension list and removes it from the start of the extension description to aid clarity.

I agree that it would still be nice to provide a way to filter installed extensions and maybe they should also be grouped together.

**Comment by jaysoo** [comment]
Closing since the vscode revamp removed this screen. This is something we're considering for Nx, so suggestions can go there https://github.com/nrwl/nx.
