### ISSUE TITLE
Generators for @nativescript/schematic not showing up

### ISSUE THREAD

**Issue by ITServicesAM** [nrwl/angular-console#276]
the @nativescript/schematics adds features to the default generators of @angular/cli. In Angular Console we can add this schematics to the project but there are no generator commands available and the default ones always use @schematics/angular:component  explicitly for exapmle.

Is it possible to make the @nativescript/schematics available in the Angular Console?
BTW its such a nice little helper!!! congratz

**Comment by Jonatthu** [comment]
I can confirm this is happening too.
