### ISSUE TITLE
[enhancement] Visual indication in the Open tab

### ISSUE THREAD

**Issue by MortenDals** [nrwl/angular-console#277]
The import/open tree structure text color is all "grayed out", and makes it very difficult to read. I get the idea of wanting to indicate that just picking a folder is not enough, but when you use "grayed out" for parents node that contains the correct child node it makes it look like there aren't any angular project in the tree at all. At the same time, since the contrast is so low for the text, finding the project is quite a bad experience, as you really have to strain your eyes to read the text.

**Comment by mrmeku** [comment]
We use the operating systems native file picker now=
