### ISSUE TITLE
Unclear when command has completed

### ISSUE THREAD

**Issue by pburkindine** [nrwl/angular-console#283]
Currently it's not clear (unless you know what to expect) when commands have completed.  It would be good if the `system exited with code 0` or a friendly map of same could be shown.

**Comment by mrmeku** [comment]
This was a great suggestion @pburkindine. Here's what we have now via a2504734035c9d6af02d19ab76e9b36398857bd0

For a status code of 0: 'Process completed 🙏';
For a status code of non 0 = 'Process failed 🐳';
