### ISSUE TITLE
Same command leads to multiple background tasks

### ISSUE THREAD

**Issue by jaysoo** [nrwl/angular-console#288]
When the user runs the same task multiple times, it should not result in multiple background tasks.

For example, if I run `ng serve example` three times with the same options, and a fourth time with different options, then I see the following.

<img width="1792" alt="screen shot 2018-10-22 at 1 10 22 pm" src="https://user-images.githubusercontent.com/53559/47306999-e200a200-d5fb-11e8-9d15-164bfba05be2.png">

This leads to UI clutter, and may confuse users. At the very least, we should probably reuse commands with same options.

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
