### ISSUE TITLE
Cannot locate node_modules directory

### ISSUE THREAD

**Issue by abidmix** [nrwl/angular-console#291]
Just did a trial run of your executable on a windows 10 Pro machine, 64 bit

On running ng serve/build, I get the error : "cannot locate node_modules directory" . Yet this directory exists and has the necessary files required.

![image](https://user-images.githubusercontent.com/12702893/47312329-13806a00-d60a-11e8-8621-3739028a07e8.png)

Same issue happens if I directly execute the command in the command prompt

![image](https://user-images.githubusercontent.com/12702893/47312699-09ab3680-d60b-11e8-9ef9-8a4b2c542fff.png)

It seems some thing is off with the generated configuration.

**Comment by manekinekko** [comment]
Hi @abidmix thanks for reporting this issue. Could you provide the exact steps to reproduce this issue?

**Comment by chauey** [comment]
I used Angular Console standalone app to create a workspace. Then used the plugin for VSCode to create app with e2e. After installing packages and running ng e2e, I got the same error.

**Comment by chauey** [comment]
I think this happens if generating the application using the wrong Angular schematic instead of the Nx schematic.

**Comment by rajarathod** [comment]
I am also facing the same issue. Can anyone provide the solution

**Comment by chauey** [comment]
@rajarathod make sure when you generate the application, that it is with the @nrwl/schematics

![image](https://user-images.githubusercontent.com/5130533/53102894-2a56af00-355f-11e9-86ed-1d1e3eaca464.png)

If that does not help, then I don't know what else as that was the only reason in my instance.

**Comment by rajarathod** [comment]
I have taken that project from github and trying to run that
