### ISSUE TITLE
Portable version for Windows

### ISSUE THREAD

**Issue by deanapeterson** [nrwl/angular-console#300]
Some of us enterprise developers don't have admin access to install stuff.  If you could create a portable version that would be great.

**Comment by mrmeku** [comment]
Working on this now. This will come in the form of an extension for VS Code / Webstorm

**Comment by mrmeku** [comment]
We now offer a .zip of our unpacked windows application and will do so for all our future releases. Here is a link to our latest release: https://github.com/nrwl/angular-console/releases/download/v7.3.0/win-unpacked.zip

Thanks for the great feature request!
