### ISSUE TITLE
Using Angular Console with schematics prompts is problematic

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/angular-console#309]
Using Angular Console with Angular CLI v7 is problematic due to the schematic prompts. You can use the GUI to go through the options, but the process will halt for any unanswered fields, even if optional.

<img width="798" alt="screenshot 2018-11-01 23 33 23" src="https://user-images.githubusercontent.com/9163179/47897336-8c639b00-de2e-11e8-8f5d-7f854bcff9de.png">

**Comment by mrmeku** [comment]
Fixed by https://github.com/nrwl/angular-console/pull/323 and https://github.com/nrwl/angular-console/pull/312
