### ISSUE TITLE
[blog request] Angular Console Architecture

### ISSUE THREAD

**Issue by adammedford** [nrwl/angular-console#314]
I'd like to request an article discussing the architecture and design decisions that were made while developing Angular Console. I wasn't sure where else to put this but I thought it would be of interest to other people viewing/using this project. 

I lead development on a number of large web based Angular applications and I'm always trying to keep tabs on what everybody else is doing. When an open source project comes along that is more than just another 'To-do List' app I'm all over it. After spending a fair amount of time reviewing the code I found a lot of decisions that immediately made sense to me - but there were still a number of surprises.

### GraphQL instead of standard REST
I understood the desire to have a separate server running on the client for file operations but without a DB or separate backend the GraphQL was unexpected. My assumption has been that you wanted to shift the complexity of configuring Express routes to declaring a GraphQL schema.

### Lack of NgRx
I imagine this was driven by the adoption of Apollo since it has an internal store. It still seems 'off message' that as such big advocates of NgRx and your Data Persistence addons that both were dropped in favor of a library I don't recall seeing Nrwl endorse previously.

I'd be interested in hearing about these and any other challenges that you might have encountered during development. Of course, I recognize that this encroaches on the type of thing you charge your clients for. No response is necessary - I can take a hint. I look forward to your future articles either way.

**I sincerely appreciate all the work y'all have already done to help us build cool stuff.**

**Comment by mrmeku** [comment]
This blog post is in the works! Stay tuned :)

**Comment by mrmeku** [comment]
Fixed! https://www.youtube.com/watch?v=YzkMFFkzrls
