### ISSUE TITLE
Hitting the remove button too quickly on a workspace generates an error

### ISSUE THREAD

**Issue by mrmeku** [nrwl/angular-console#315]
If I'm removing workspaces and I click the remove button twice (one initially and once when it's animating out) our graphql api throws an error.  We shouldn't throw an error if we send a request to remove a workspaces which as already been removed

**Comment by vsavkin** [comment]
@mrmeku can you provide a screenshot? I cannot repro it. 

The act removing is a PUT like operation, so it doesn't depend on the server status. So I'm a bit surprised you are seeing an error.
