### ISSUE TITLE
Compilation errors break test detailed status

### ISSUE THREAD

**Issue by vsavkin** [nrwl/angular-console#320]
Repro:

- Create a new CLI project
- Start running tests with --watch
- Introduce the compilation error by say, removing a quote (`describe('AppComponent, () => {`)
- You will see the error being displayed
- Fix the error
- The terminal will display the correct status (3 of 3 are successful), but the detailed status won't

**Comment by jaysoo** [comment]
Looks like there was some unexpected output that clobbered the state.

Just tested locally with my fixes, and it seems to be working now.

Steps:

1. Run test with watch.
2. Tests all passed.
3. Introduce compile error.
4. See build failed.
5. Fix error.
6. Tests pass again.
7. Introduce expectation error.
8. See tests failed.
9. Fix tests.
10. See tests passed.

![test-run](https://user-images.githubusercontent.com/53559/48143602-25564400-e27d-11e8-88fd-6274d42ff788.gif)
