### ISSUE TITLE
Making the ng serve process a bit clearer

### ISSUE THREAD

**Issue by rohitsodhia** [nrwl/angular-console#329]
Currently, when you serve an app, it's not clear when it's building, serving, errored, or stopped. I just recently started using the app, but I had a situation already where I wasn't sure why my app wasn't (yet) loading, and the console at the bottom of the console didn't show anything. Text or visual indicators of the current state (and maybe in the titlebar?) would definitely help a lot. When serving from the CLI, I can easily tell where I am and the history. This may also be because in the console output, it only takes up about a third of my window (two third are just blank black, which makes it unclear what's happening).

**Comment by mrmeku** [comment]
@rohitsodhia Are you running the latest version of console? We now parse what is printed to STDOUT and show you the information you requested. It should look something like this: 
![image](https://user-images.githubusercontent.com/8085051/49235455-21bf6400-f3c8-11e8-8e70-68f1c6caa598.png)

If you're running the latest version and I misinterpreted what you meant please reopen the issue and tell me.
