### ISSUE TITLE
[Feature]: i18n Management interface

### ISSUE THREAD

**Issue by rskendzic** [nrwl/angular-console#410]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality
User interface for management, maintenance and updating of `.xlf` files.

#### What is the use-case or motivation for changing an existing behavior?

There is a plugin for [Vue UI](https://morningstar.engineering/vue-ui-a-first-look-916600d9a918) that is very useful for handling all translations called [Vue-18n](https://kazupon.github.io/vue-i18n/guide/started.html). 
At the moment maintenance of the `.xlf` files is rather troublesome. Extracting this functionality to Console would give flexibility in management and maintenance of translations.

**Comment by mrmeku** [comment]
This sounds like a great feature to add! We'll definitely look into doing it after we have handle some more important architectural changes to Console

**Comment by Chris-43** [comment]
I think I have found some stuff that needs a look. Like any bug, they make themselves  "unreliable." Today Console behaved  it was much better than the last used it 
Attached are screenshots of what happened.

![01](https://user-images.githubusercontent.com/2609706/58767678-1575b880-855d-11e9-8518-34c765ee9d55.PNG)

![02](https://user-images.githubusercontent.com/2609706/58767692-3938fe80-855d-11e9-94fa-d0d898d9471e.PNG)

![03](https://user-images.githubusercontent.com/2609706/58767705-6e455100-855d-11e9-8d75-febda49ab56b.PNG)

![04](https://user-images.githubusercontent.com/2609706/58767711-7a311300-855d-11e9-86a2-a756d309a77a.PNG)

![05](https://user-images.githubusercontent.com/2609706/58767717-8e751000-855d-11e9-9133-99d282ff3686.PNG)

![05a](https://user-images.githubusercontent.com/2609706/58767721-a056b300-855d-11e9-8415-9540a3f6032c.PNG)

![06](https://user-images.githubusercontent.com/2609706/58767747-de53d700-855d-11e9-9f13-9f2754c2cfd3.PNG)

![06a](https://user-images.githubusercontent.com/2609706/58767756-f0357a00-855d-11e9-8b32-1e3b3fe04883.PNG)

![07](https://user-images.githubusercontent.com/2609706/58767767-00e5f000-855e-11e9-9ee5-48796e98d567.PNG)

![08](https://user-images.githubusercontent.com/2609706/58767771-0cd1b200-855e-11e9-9b0a-7cefc2f08607.PNG)

Thats all Folks

Chris

**Comment by jaysoo** [comment]
Closing this since we've revamped UX for vscode.
