### ISSUE TITLE
Remove node installation route in favor of specifying node path

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/angular-console#411]
On a brand new MacBook Pro, I installed Angular Console and went through the node process. After the node installation had completed, Angular Console was stuck on "Downloading Node" for several minutes. I quit Angular Console and opened it back up and it works fine.

**Comment by mrmeku** [comment]
Thanks Jeff. I'll take a look.

**Comment by zyrain** [comment]
I just had the same behavior on Windows 10.

**Comment by mrmeku** [comment]
@jeffbcross I've updated the bug description to indicate that we are no longer going to maintain installing nodejs for you. We don't do a good job of it and allowing user's to specify their own node / use electron if they don't have one installed feels like a better UX
