### ISSUE TITLE
OSX DMG corrupt?

### ISSUE THREAD

**Issue by pburkindine** [nrwl/angular-console#424]
I am having trouble with the OSX DMG.  Every time I try to copy into apps, I get an error 'The Finder can't complete the operation because some data in "Angular Console" can't be read or written.  PFA screenshot.

![screen shot 2018-11-30 at 10 34 10 am](https://user-images.githubusercontent.com/20215564/49302065-a921db80-f48b-11e8-9d02-0fa41d99510f.png)

**Comment by mrmeku** [comment]
@pburkindine We just cut a new release a few minutes ago and I was able to pull down a fresh image and install it successfully. Would you mind trying our latest release and reporting back on whether you still have trouble?

**Comment by mrmeku** [comment]
@pburkindine Feel free to reopen this issue if you continue to have trouble.
