### ISSUE TITLE
[bug] NgRx extensions don't add schematics despite showing 'Installed'

### ISSUE THREAD

**Issue by adammedford** [nrwl/angular-console#426]
Two extensions are listed in the extensions lists 
1. @ngrx/effects
2. @ngrx/store

Neither actually adds schematics because the @ngrx/schematics is the correct package - but not listed.

The other two have an 'ng-add' schematic that isn't used for whatever reason.

**Comment by mrmeku** [comment]
Thanks for the details Adam. I'll fix this for the next release
