### ISSUE TITLE
Filter out private schematics

### ISSUE THREAD

**Issue by devversion** [nrwl/angular-console#433]
Hi, after playing with Angular Material within the Angular Console, I realized that there is a schematic that is supposed to be "hidden" / "private".

<img width="1036" alt="screenshot 2018-12-07 at 11 16 24" src="https://user-images.githubusercontent.com/4987015/49642098-61aec880-fa12-11e8-9f2c-dd07252ca12e.png">

The _ng-add-setup-project_ schematic is marked as `private` in the schematic collection and shouldn't show up here, right?

Currently the console only seems to filter for `hidden: true`, but `private: true` also implies that `hidden` is set to `true`.

See https://github.com/angular/angular-cli/blob/6449a753641340d8fc19a752e1a1ced75f974efa/packages/angular_devkit/schematics/collection-schema.json#L45-L53

**Comment by mrmeku** [comment]
Great suggestion. I'll get that sorted today
