### ISSUE TITLE
Please provide a User Installer on Windows

### ISSUE THREAD

**Issue by modul8com** [nrwl/angular-console#439]
Corporate users of the Angular CLI typically can't install application on their system via a "System Installer", which installs the application for all the users of the machine... but if there would be a "User Installer" which only installs the application for the current connected user, then it might work... at least it does work here for VS Code ;).
Or a way to "npm install angular-console" might work too.

**Comment by mrmeku** [comment]
We now offer a .zip of our unpacked windows application and will do so for all our future releases. Here is a link to our latest release: https://github.com/nrwl/angular-console/releases/download/v7.3.0/win-unpacked.zip

Thanks for the great feature request!
