### ISSUE TITLE
Incorrect label when creating a library

### ISSUE THREAD

**Issue by vairamsvsjdo** [nrwl/angular-console#443]
Incorrect label when creating a library

Expected outcome: 
Label should read "A directory where the **library** will be placed"
Actual outcome:
"A directory where the **app** will be placed"

**Comment by vsavkin** [comment]
Angular Console reads those labels from packages providing scheamtics. I think you found an issue with Nx (https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/library/schema.json#L18)
