### ISSUE TITLE
Trying to run v7.0.0 and v7.1.1 gives error

### ISSUE THREAD

**Issue by st-clair-clarke** [nrwl/angular-console#464]
Hi,
If I try to run angular console with the above versions I get the following message and the program fail to run:

Error when running 'ng ...'. Message: "File not found: J:\workspace\ngnx\node_modules\.bin\ng.cmd"

I have tried uninstalling and reinstalling with the same result. Is there a cache somewhere on the system?

I am using Windows Installer on Windows 10.

**Comment by mrmeku** [comment]
@st-clair-clarke This will be fixed in our next release (if it wasn't already fixed by our last release). Keep a look out this week for it

**Comment by bampakoa** [comment]
@st-clair-clarke I think you need to have local CLI installed cause I get the same error even in 6.0.0 version 

@mrmeku
