### ISSUE TITLE
Feature: Ability to a group applications in the projects list

### ISSUE THREAD

**Issue by ndcunningham** [nrwl/angular-console#467]
I think it would be great if I could group the applications in the project list tab first then the libraries after.

Currently, I don't understand how it is ordered. Maybe based on creation date?

**Comment by mrmeku** [comment]
It's currently ordered via the order in `angular.json`. But in general I think having a standard ordering of apps then libs (alphabetical) would be better. Lets do it

**Comment by mrmeku** [comment]
This issue applies to the old electron version of vscode which is now deprecated.
