### ISSUE TITLE
All commands in system console history

### ISSUE THREAD

**Issue by madmxg** [nrwl/angular-console#468]
All commands that have been processed remain in the console history (try `history` in system terminal)

![image](https://user-images.githubusercontent.com/1833499/51002438-4c164c80-1544-11e9-9ff6-879cc589d4ef.png)

**Comment by mrmeku** [comment]
I could definitely see how that would be annoying. I'll get that fixed. It'll require bundling node-pty for os x and linux rather than just windows (as is done right now)

**Comment by mrmeku** [comment]
I have a fix! Once its merged I'll try to cut a new vscode release assuming everything else is stable
