### ISSUE TITLE
WebStorm Plugin

### ISSUE THREAD

**Issue by fkolar** [nrwl/angular-console#470]
This is more like a feature request and a placeholder for the AngularConsole Plugin for the Webstorm and Intellij IDE. 

I think it should not be that hard to have this plugin for this IDE as I have written some already, but I just want to make sure I dont duplicate somebody's work! Or if somebody is already working on this let this be a placeholder to track this.

Also I just looked over how the angular-console repo is done and how the vscode is implemented and I must say `vscode` is way straight forward compared Intellij.

In Intellij there is more native way of doing it with way more code. If we want to use the same webapp and I assume `yes` then **JAVA** has this `JavaFX` extension API which has some HTML5 web rendering support. 

Thanks, 
Frank

**Comment by fkolar** [comment]
Thanks for update, just wanted to make sure I dont duplicate somebody's work! I will start looking into this then. I think I should be able to have some space at the end of Feb, when I get back from US.

**Comment by mrmeku** [comment]
@fkolar That sounds great. Whenever you have a question or make some progress please don't hesitate to reach out on this bug! If you start to make a good deal of progress we can add you to the core team if that's something you're interested in

**Comment by mrmeku** [comment]
@fkolar Any updates?

**Comment by fkolar** [comment]
Hey @mrmeku,  Finishing up some other tasks and so far it seems  my previous statement `I think I should be able to have some space at the end of Feb` should work out !

**Comment by fkolar** [comment]
@mrmeku  I think I should be able to start looking at this already this weekend if everything goes well.  Still so many things to do but the first plan would be more to get familier  so that I can do now:

- Create a basic IDE plugin shell that can:
   -   Show a Dedicated Panel in the `ToolWindow` area and using `JavaFX` render any HTML website with help of its `webview`
   -  Have Entry point that can listen for Opening a Project (Module) and closing for the future initialization ( start/stop of the background thread)
   - Create set of placeholder actions that can (something that I would expect it should do):
      - Right-click in the project Windows on a directory  and show up a popup and have option to create Angular Based Element (component, module, service,...)
       - Right-click on the editor and based on the context and current AST node pull out some information, so maybe when I click on the class I can have action to add/update addional properties to `@Component` decorator
       - Not sure if this above would be supported by current console by adding extra routing so I can pre-populate it with the info,... again I dont want to get ahead of myself. 

- Push this to my github so you can start checking this out and keep filling more and more functionality

- Install `VSCode` with current `Console plugin` to actually see what is possible, I only look at the console so far only at the code and run it with ng cli.


**Last point:** Do you have some kind of `slack channel`? I am sure once I get into this more I will have some concrete questions! It would be nice to have!. my email would be fkolar@icloud.com

**Comment by fkolar** [comment]
Created new repo, where in readme you can see my plan:
https://github.com/fkolar/ng-console

**Comment by fkolar** [comment]
@mrmeku @vsavkin Where I can find icons for project, generate, tasks, extensions, ... actions that you use in VSCode ?

**Comment by mrmeku** [comment]
@fkolar Sorry for the delay on getting back to you! Let me invite you to our slack channel

**Comment by mrmeku** [comment]
@fkolar Forgot to mention. Your repo is looking great. I especially love how the readme keeps track of your progress

**Comment by jaysoo** [comment]
Closing this since we're focusing just on vscode for now. WebStorm/IntelliJ will be useful, so we can consider it again in the future.
