### ISSUE TITLE
Invoking VSCode Plugin?

### ISSUE THREAD

**Issue by JefferE** [nrwl/angular-console#475]
Just got the email announcing VSCode plugin for Angular Console and I installed it - but can't figure out how to invoke it from VSCode. I am missing the purpose of having a plugin for this?

**Comment by jfreal** [comment]
I'm having the same issue.

**Comment by mgbee8** [comment]
I am having the same issue.

**Comment by jeffbcross** [comment]
+1 we should make it more obvious

**Comment by mrmeku** [comment]
Will be closed by https://github.com/nrwl/angular-console/pull/487 :) 

Sorry about all the confusion everyone. I rushed the release and didn't make any documentation. But soon we'll have a nice huge button to open console. Expect a release this week!

**Comment by mrmeku** [comment]
Our next release will have a big button in the activity bar that you can push to activate the extension. We will release by Friday!
