### ISSUE TITLE
Feat: Bootstrap Extension

### ISSUE THREAD

**Issue by bryananthonylewis** [nrwl/angular-console#485]
Would it be possible to add a bootstrap extension that installed bootstrap the Angular way? 

This would help me out quite a bit. We always add Bootstrap to our projects.

I'm an Angular beginner so, I'm unsure if I'm talking the same lingo and am unsure if this is the right place to add this post. I can always remove this if needed.

**Comment by mrmeku** [comment]
Sure can! I think ng-bootstrap has an ng-add schematic

**Comment by mrmeku** [comment]
https://github.com/nrwl/angular-console/blob/a2504734035c9d6af02d19ab76e9b36398857bd0/libs/server/src/lib/api/read-extensions.ts

**Comment by bryananthonylewis** [comment]
That is great news! Thanks a ton!
