### ISSUE TITLE
[Feature request] Add Angular Console to the Activity Bar

### ISSUE THREAD

**Issue by Crackroach** [nrwl/angular-console#489]
Currently when opening the Angular Console app in vscode it opens a new tab, cluterring the workspace. It would be great to have the Angular Console directly in the Activity bar on the side. Provided with a keyboard shortcut for ease of use would be nice too.

**Comment by mrmeku** [comment]
Will be closed by https://github.com/nrwl/angular-console/pull/487 :)

**Comment by mrmeku** [comment]
Our next release will have a big button in the activity bar that you can push to activate the extension. We will release by Friday!

**Comment by Crackroach** [comment]
Nice! Having Angular Console directly inside Visual Studio Code is a great feature. Thank you for taking the time to consider this request.

**Comment by mwight4** [comment]
Was this removed recently? I can't seem to get VSCode to show it anymore and Im not sure how to get into the tool inside VSCode without it
<img width="1108" alt="Screen Shot 2019-04-04 at 7 13 03 PM" src="https://user-images.githubusercontent.com/6342882/55594470-c1418a00-570d-11e9-9f54-8d86032f8add.png">
