### ISSUE TITLE
How to use in VS Code?

### ISSUE THREAD

**Issue by ryanlangton** [nrwl/angular-console#511]
How about some instructions on how to use the Angular Console w/ the VS code extension? I've been looking everywhere and haven't found any (I'm talking about just opening it in VS code, I know how to use the standalone VS code). Please add this to the readme page after installing the extension in VS code.

**Comment by Kamilnaja** [comment]
@ryanlangton for me this is really easy.
ctrl + shift + p and select Angular console

**Comment by ryanlangton** [comment]
Fantastic, thanks! Please add it to the readme/splash screen. It's not apparent how to use.

**Comment by sumigoma** [comment]
The next release will apparently add a big tab button to the Activity Bar, once this gets completed.
https://github.com/nrwl/angular-console/pull/503

**Comment by mrmeku** [comment]
We have released! There is now a GIF in our README.md that show you how to activate the extension :D
