### ISSUE TITLE
Error when reading the workspace data. v7.3.0

### ISSUE THREAD

**Issue by Crackroach** [nrwl/angular-console#521]
## Problem
Angular Console VSCode extension cannot run project that is not at the root of a workspace/folder.

I cannot open the project in the Angular Console VSCode extension (version 7.3.0). The screen stays empty and there is no way to do anything with it (see screenshot below).

## Environment
My workspace looks like this:
```
.<Workspace root>
├── client
│   └── [The actual Angular application]
├── Documentation
│   └── [Project documentation]
└── Firebase
    └── [Firebase related stuff]
```

## What I tested

When I try directly from the desktop application there is no problem. The Angular Console app opens and load the project. I can even `ng serve` my apps. I cannot say which version as I haven't found where it is displayed.

I tried opening the angular project as root and the Angular Console extension did load and I was able to `ng serve` the app.

![image](https://user-images.githubusercontent.com/5933612/52421717-a6161d80-2ac2-11e9-8f02-881c39d1d3cf.png)

**Comment by cmtp** [comment]
I have the same problem when I try to load my workspace.

![image](https://user-images.githubusercontent.com/9135312/52515267-97795480-2bef-11e9-918b-89e048abe87a.png)

**Comment by mrmeku** [comment]
Great point guys! I think we can do a better job of messaging that Angular Console needs to be opened at the root of an Angular CLI workspace in its current form.
