### ISSUE TITLE
new-workspace command not found

### ISSUE THREAD

**Issue by CarstenLeue** [nrwl/angular-console#536]
Creating a new workspace from the vscode plugin yields:

Error when running 'ng new'. Message: "File not found: XXX\.vscode\extensions\nrwl.angular-console-7.3.1\assets\new-workspace.cmd"

**Comment by laljikanjareeya** [comment]
I am also facing same issue.

**Comment by isarhoo** [comment]
+1

**Comment by mrmeku** [comment]
Apologies, I intended to completely remove the new workspace screen from the vscode extension. Can you all elaborate on how you were able to find it? I'm planning on adding the feature into VSCode in a later release

**Comment by laljikanjareeya** [comment]
Please find below vscode configuration and angular console is latest version.

![image](https://user-images.githubusercontent.com/46327204/52861006-212ca300-3157-11e9-86e9-3a3985ad39b3.png)

**Comment by addinfinity** [comment]
For me works from desktop application.
But same error if I use VSCode Extension. I am using latest version of extension

**Comment by mrmeku** [comment]
This will be fixed in our next release (due sometime this week or early next week)
