### ISSUE TITLE
404 when attempting the .deb download

### ISSUE THREAD

**Issue by oleersoy** [nrwl/angular-console#539]
This is the return value for the `.deb` download selection:

https://github.com/nrwl/angular-console/releases/download/v7.3.0/AngularConsole_7.3.0_amd64.deb

But it renders as a 404.

**Comment by mrmeku** [comment]
This is the updated URL. Sorry for the confusion, electron updater makes us name our packages in a specific way and we had to rename the .deb https://github.com/nrwl/angular-console/releases/download/v7.3.0/AngularConsole-7.3.0.deb
