### ISSUE TITLE
VSCode integration: unable to copy/paste from Generate > serviceWorker

### ISSUE THREAD

**Issue by supdegrave** [nrwl/angular-console#541]
EXPECTED: ability to select / copy / paste text output in the lower pane when an error occurs in Generate view. 

REPRO: 
Launch VSCode, open Angular Console extension
Click Generate, then serviceWorker
Enter project name in the top field. 
At this point, I get an error (see screenshot). 
Select the error text, copy (locally, Cmd+C on macOS).
Paste into a text document. 

ACTUAL RESULT: 
Previous entry in copy buffer is pasted. There is no obvious way to select / copy / paste. 

![image](https://user-images.githubusercontent.com/5695160/52575372-5f0b8d80-2e1e-11e9-8a71-203dc1b2b074.png)

**Comment by mrmeku** [comment]
Yeah, this is a known error. I'm going to use the issue you filed to track it. Thanks so much for taking the time to file it!

**Comment by mrmeku** [comment]
Blocked on a VSCode bug I've filed: https://github.com/Microsoft/vscode/issues/68799

Its not just Angular Console, its any VSCode webview which makes use of iframes

**Comment by mrmeku** [comment]
@supdegrave and @everyOneElseWhoCaresAboutThisBug if you could give the vscode bug a thumbs up it'll dramatically increase the likely-hood it'll get noticed by their team

**Comment by mrmeku** [comment]
@supdegrave We now use vscode's native terminal so this feature is officially fixed!
