### ISSUE TITLE
VSCode extension: unable to generate serviceWorker

### ISSUE THREAD

**Issue by supdegrave** [nrwl/angular-console#542]
REPRO:
Launch VSCode, open Angular Console extension
Click Generate, then serviceWorker
Enter project name in the top field.

EXPECTED: ability to generate a serviceWorker from Generate view.

ACTUAL RESULT: The following error message appears in the console-looking lower part of the Generate view. 

![image](https://user-images.githubusercontent.com/5695160/52575546-adb92780-2e1e-11e9-814e-2239972c76cd.png)

**Comment by mrmeku** [comment]
@supdegrave I generated a fresh workspace and was able to generate a service worker for it without error. Can you give me more details about your specific workspace? This might be a problem with your repo rather than console, but I'd love more details to make sure

**Comment by supdegrave** [comment]
@mrmeku What sort of information would you like?

**Comment by mrmeku** [comment]
Ideally a way for me to clone it to take a full look. But alternatively, if you could paste your package.json file here for me to look at that would be really helpful
