### ISSUE TITLE
[VSCode] feat: Add File actions which run architect targets for the project.

### ISSUE THREAD

**Issue by FrozenPandaz** [nrwl/angular-console#555]
## Current Behavior

You have to navigate to the project which you're working on in order to run commands

## Expected Behavior

You should be able to trigger architect commands from the file explorer/command palette similar to triggering file formatting

### Scenario

1. You open a workspace
2. You get to work on a component (`apps/app1/src/app/navbar/navbar.component.ts`).
3. You want to test the work you did:
  a. You go to the file explorer and right click the File where there's an entry called `Test Project`
  b. You activate the command palette and type `Test Project` and execute
4. The project containing the file (`app1`) should have it's `test` target run.
5. Output should appear

## Additional Info:
A project contains a file if the file is in its projectRoot.
Only commands which are available for the project should show up.

**Comment by FrozenPandaz** [comment]
cc @mrmeku

**Comment by mrmeku** [comment]
We did it!
