### ISSUE TITLE
VSCode extension is cumbersome to navigate without shourcut bar

### ISSUE THREAD

**Issue by Tiedye** [nrwl/angular-console#556]
I believe the change in #489 had the added consequence of removing the shortcut bar from the angular console window.  It's good having it in the activity bar, but I find the console cumbersome to navigate when I have to open the angular console tree view just to get the shortcut to open a new tab for the console and then close the old console tab as it doesn't replace the old console tab.

When I first tried the extension (before the shortcut bar was removed) I absolutely loved the workflow of provisioning a new project, I had the file tree view open on the left, and the console open on the right.  I was generating components, seeing them update in the tree, making any changes I wanted to the file, and all the while doing a little bit of feature discovery in the console _without_ having to constantly hide the file tree to swap between different console views.  It was so wonderfully efficient.  Now today when I went to do the same, I found my workflow significantly encumbered by this seemingly small adjustment.

Sorry for the rant, my thoughts on this issue are very refined yet, in summary having the navigation for the console close to the console was a better UX and could we get a setting to enable that shortcut bar again please.

![The Shortcut Bar](https://user-images.githubusercontent.com/6187173/53124486-7a1a8380-3529-11e9-9d2c-33cb8864308a.png)

**Comment by mrmeku** [comment]
@Tiedye I'll make this toggleable in the settings menu because I also miss it. The other memebers of the console team thought it was kinda yucky to have the side bar inside of VSCode since it already has its own sidebar, but I think there's no harm in exposing it for those who want the functionality

**Comment by Tiedye** [comment]
@mrmeku How's this goin?

**Comment by mrmeku** [comment]
This will be added to our next release of vscode

**Comment by mrmeku** [comment]
@Tiedye We have instead decided to use keyboard driven navigation for the use case that you were describing (in addition we are rewriting the entire front end to feel vscode native / launch faster)

Sorry to have never been able to release this feature for you as you requested it
