### ISSUE TITLE
can not run package.json scripts

### ISSUE THREAD

**Issue by giniedp** [nrwl/angular-console#559]
i am not able to run my package.json scripts. Neither in standalone app nor in VSCode extension.

From VSCode extension, running a script results in this error

```
yarn run setup

/Users/alex/.yarn/bin/yarn.cmd: line 1: @echo: command not found
module.js:550
    throw err;
    ^

Error: Cannot find module '/Users/alex/repositories/go/src/gbc3/%~dp0\yarn.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Process failed 🐳
```

mention it tries to access the `yarn.cmd` but i am on OSX

From Standalone app the command is logged but no error is shown
```
yarn run setup
```

The structured output shows the message
```
Task failed. Please check terminal output for more details.
```

Running the commands does work when done manually from terminall
```
yarn run setup
npm run setup
```

I am on OSX 10.14.2 (18C54)
VSCode Version 1.31.1 (1.31.1)
Angular Console VSCode Version 7.3.1
Angula Console Electron Version 7.3.0 (7.3.0)

**Comment by giniedp** [comment]
if i remove the `yarn.lock` file (or rename it) Angular Console tries to rune the scripts with `npm`. This works fine

**Comment by giniedp** [comment]
so i was on yarn 1.6.0 and it seems i had a legacy folder unter $HOME/.yarn where yarn seems to be installed. I updated yarn via

```
npm install yarn -g
```

to 1.13.0 but the system was still getting yarn 1.6.0 from the .yarn folder. Now i removed the .yarn folder and the system grabs yarn 1.13.0 and Angular Console works fine now.

**Comment by mrmeku** [comment]
@giniedp Sounds like this is worth a bit of investigation if the presence of a yarn.lock file was cauing use to try to use yarn.cmd on non windows

**Comment by vsavkin** [comment]
Fix https://github.com/nrwl/angular-console/pull/562
