### ISSUE TITLE
download link to deb broken

### ISSUE THREAD

**Issue by magnattic** [nrwl/angular-console#560]
On angularconsole.com, the deb download link points to
> https://github.com/nrwl/angular-console/releases/download/v7.3.0/AngularConsole_7.3.0_amd64.deb

That file doesn't exist. (404)

Should probably be
> https://github.com/nrwl/angular-console/releases/download/v7.3.0/AngularConsole-7.3.0.deb

**Comment by mrmeku** [comment]
@magnattic Thanks for pointing that out. We'll get that fixed up shortly

**Comment by JamesHenry** [comment]
Thanks @magnattic, this should be fixed now
