### ISSUE TITLE
[vscode]: Keyboard shortcuts not responding

### ISSUE THREAD

**Issue by bampakoa** [nrwl/angular-console#566]
Keyboard shortcut keys for VSCode built-in commands are not responding when the extension has the focus.

**Comment by mrmeku** [comment]
@bampakoa I've filed this issue with the vscode team: https://github.com/Microsoft/vscode/issues/70339

If you could leave a thumbs up on the issue it might help it get addressed faster. I'm really sorry there's not more I can do to fix the bug. I've tried a number of things but there's no escaping our current need to embed angular console within an iframe which causes the buggy behavior you've described

**Comment by bampakoa** [comment]
@mrmeku please note that it works correctly in Linux environment

**Comment by bampakoa** [comment]
@mrmeku I checked also in Windows and it works correctly. Thanks!
