### ISSUE TITLE
Is it possible to generate projects based on a config file?

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [nrwl/angular-console#568]
Hello,

If I have a configuration file in a format that could be read by Angular Console, will it be possible to read it and create the folders, projects, set the dependencies and routing and create components based on that?

I will export that config file from another application and will ask the user to use it in Angular Console to generate it.

Please let me know.

**Comment by mrmeku** [comment]
@VigneshVaidyanathan What's the difference between the configuration file's you're proposing and   a workspace schematic?

**Comment by VigneshVaidyanathan** [comment]
I have not used schematics extensively but as far as I have used, it helps us to set the settings for the cli commands that we are going to run. Eg, the default stylesheet, spec file etc. 
I wanted to have like a json, where it says all the components it needs to create with the name, if it needs a service file etc. 
So essentially I will be importing a json file that will create my entire application with components, services, even model files and modules and implement routing with lazy loading as well. This way we can simplify the app kickstart to customize it within minutes and still follow the general pattern for effectiveness

**Comment by mrmeku** [comment]
@VigneshVaidyanathan That's precisely what NXs workspace schematics are meant for. Let me link you some docs in case they might be helpful for you

Blog post - https://medium.com/@simonb90/create-workspace-specific-schematics-with-nrwl-nx-9a1b7cd65345
Official docs - https://nx.dev/angular/api/workspace/schematics/workspace-schematic
