### ISSUE TITLE
Feature : Ability to run cli extensions that was not listed.

### ISSUE THREAD

**Issue by manudss** [nrwl/angular-console#579]
As a user, if I found a angular schematics, that is not listed in all cli extension. I would like to run it, without exit angular-console. 

This would be a fields where enter the name of shcematics. And after, will run it, in the same way of other cli extension.

**Comment by mrmeku** [comment]
@manudss I think a better solution is just to list all of the schematics that we can and add non-listed packages as we find them. Can you tell me which schematics you wanted to use that wasn't inside console? I'll add it to our list

**Comment by manudss** [comment]
One, that I have needed was : akita-schematics 
https://github.com/datorama/akita-schematics 

Tehn you can find a list of shcematics used by intellj, that is more complete : 

https://github.com/JetBrains/intellij-plugins/blob/master/AngularJS/resources/org/angularjs/cli/ng-packages.json

Another : @briebug/cypress-schematic -> https://github.com/briebug/cypress-schematic To add Cypress into project

**Comment by mrmeku** [comment]
The intelli J list is really a great resource. I'll try to merge all the schematics in that list into our repo (as well as the other two you mentioned)
