### ISSUE TITLE
Feature: Interface for managing angular.json configuration

### ISSUE THREAD

**Issue by manudss** [nrwl/angular-console#581]
It would be great, to have an interface, for easily manage angular.json file.

When we manage different application and library, and for each of then different configuration, the angular.json will begin very long and difficult to uderstrood. 

This could be as a page with common options, then a tab by each of the projects, which would show that the options of this project, or one could manage the build configurations, serve etc ...
And also for builds, manage configurations, where we could add, delete, edit, copy configurations.

This could best be presented as a page with all possible options in a big form
Or else to propose the edition of the js, via a json editor (like ace editor), configured with all the possible options of help with code completions.

**Comment by jaysoo** [comment]
This is in the latest 9.0 vscode release!
