### ISSUE TITLE
Feature: persist history of commands

### ISSUE THREAD

**Issue by dungahk** [nrwl/angular-console#588]
# Description

Not the same as #468 asked to remove, but instead, I'd like to be able to close vscode and when opening it again the history of commands is still there for me to see and possibly repeat them.

# Use case

Very good when testing schematics, sometimes I do a sequence of ng commands and with Angular Console all I need is just to revert all the files and repeat the commands, but when I close vscode I lose that.

**Comment by mrmeku** [comment]
Sounds like a great feature to add. We will do it

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
