### ISSUE TITLE
[vscode]: Defaults in production build

### ISSUE THREAD

**Issue by bampakoa** [nrwl/angular-console#605]
After upgrading to the latest version of the extension (**7.4.3**) we have noticed that the production build command has `sourceMap` set to `true` and `statsJson` enabled by default which was not in the previous versions.

Is this intentional? If yes, is there a way to override them instead of changing them manually on each build? In our case, we have an automation that uploads the whole `dist` directory automatically and we don't want to deploy stats.json and source maps on the production server.

**Comment by bampakoa** [comment]
Following the above comment, should Angular Console respect the default values from **angular.json** file? 

For example, the `sourceMap` property is set to `false` in the production configuration by default. Instead, the Angular Console tries to run the production configuration with `sourceMap` set to `true`.

**Comment by StudioTOB** [comment]
Hi bampakoa,

I have had the same issue. Setting this to false in the angular.json doesn't change it to false, the way I would have expected it to work. I've setup multiple environments at work, and this setting is easy to forget when using Angular Console. I hope there will be a solution for this soon...

**Comment by princemaple** [comment]
This issue really should gain more attention...

**Comment by mval1002** [comment]
Agreed! I come to check if there are any update on this every time I need to make a build!

It's not a deal breaker, but considering the entire purpose of AC is convenience, this is a very inconvenient issue!

**Comment by princemaple** [comment]
@vsavkin would be great if you could take a look at this.
https://github.com/nrwl/angular-console/blob/master/libs/feature-run/src/lib/target/target.component.ts#L180 this should really be whatever the config from the project is, instead of hardcoded.
