### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by devloper-404** [nrwl/angular-console#608]
Dark modes are most preferred themes for IDE these days and in VS code, Angular Console still dose not support dark mode. It would be good have a dark mode to ease out developers eyes.

**Comment by jaysoo** [comment]
@devloper-404 We have plans to add this so stay tuned!

**Comment by nixallover** [comment]
@devloper-404 In the next major release, forms in the Angular Console VS Code extension will derive their colors from your editor theme. We're planning to release it this month, so prepare for your eyes to be eased. :)

**Comment by mrmeku** [comment]
We did it!
