### ISSUE TITLE
Support custom autocomplete dropdowns

### ISSUE THREAD

**Issue by Maus3rVonDutch** [nrwl/angular-console#612]
Hi, I've created my own templates for the ngrx schematics to better suit our company's needs. I would like to have to option to add autocomplete support for my schema (like the ngrx/angular schemas have for selecting modules/projects etc.). 

I was looking at the source code of Angular Console and saw the auto complete feature is pretty much hard coded in the application. Would you consider opening this up, or provide and option to target some standard properties (like modules/projects) in our custom schemas, so we can benefit from that feature?

**Comment by mrmeku** [comment]
@Maus3rVonDutch That sounds like a great idea. Lets try to discuss a basic API on this issue. Let me outline how we currently implement autocomplete in our code base.

In `libs/utils/src/lib/completion.service.ts` we expose an API to query for completions via Graphql
The type signature is

```
interface CompletionResultType {
  value: string;
  display?: string;
}

completionsFor(
    path: string,
    field: Schema,
    input: string
  ): Observable<Array<CompletionResultType>>
```

So essentially any API we build will be given a path, field and input as parameters where a path is , a field is the schematic definition for what is being completed

**Comment by jaysoo** [comment]
Closing this due to lack of movement.
