### ISSUE TITLE
Not Adding NxModule.forRoot() when  generating application with @nrwl/schematics

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/angular-console#613]
NxModule.forRoot() not being added to app.module.ts when creating application using @nrwl/schematics.

**Versions:**
Angular Console: Version 7.4.3 (7.4.3)

Angular CLI: 1.7.4
Node: 10.15.2
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by mrmeku** [comment]
Please file an issue here: https://github.com/nrwl/nx/issues
