### ISSUE TITLE
Feature: Update configuration to Add Debug button for NestJs

### ISSUE THREAD

**Issue by Tyler-V** [nrwl/angular-console#614]
Using the Angular Console in VSCode, its a great addition and makes it convenient to launch an app and api without opening additional terminals in vscode. Thank you for that.

My questions is, how can I add a Debug task that would allow me to set breakpoints and debug NestJs? I'm assuming these tasks are pulled from the architect section in angular.json.

Is it possible to create a task that serves the app and starts the debugger to attach to the node process?

Currently I am serving the API from the angular console extension and just running VSCode - Debug from the application but it seems like this could be incorporated? Any tips?

```
{
    "type": "node",
    "request": "attach",
    "name": "Debug NestJs",
    "sourceMaps": true,
    "port": 7777
  } 
```

**Comment by mrmeku** [comment]
I think that's more of a question for NX. They publish the NestJS schematic and could easily include a file like that to make getting debug up and running easier. Could you repost the issue there?
