### ISSUE TITLE
Webstorm: Mutliple instance problem

### ISSUE THREAD

**Issue by fkolar** [nrwl/angular-console#629]
`AngularConsole` background process that is running inside Intellij IDE shuts down when opening new IDE instance. It shutdown cleanly, like `dispose project method would be called`

This is probably a sideeffect of code that I put for the wizard `new workspace` process. 

just assign it to me.

**Comment by fkolar** [comment]
We will have to introduce a `NgConsoleServerRegistry` which will track `NgConsoleServer` instances.

**Comment by mrmeku** [comment]
@fkolar We should be able to get away with using just one angular console server if need be. I tested this out with VSCode and it seems like the performance is fine even with 3 editors using the same server

**Comment by mrmeku** [comment]
But either solution is fine. We can spawn as many servers as we please!

**Comment by fkolar** [comment]
Yeah, compared to IDE  the angualar console server has small footprint, I am investigating both ways. Right now I have something ready where I can start multiple instances (with multiple ng servers) - I need to test it properly
  - There was mainly problem with the: 
          *  RPC JAVA - JS comunication as each process needs its own RPC domain to listen to
          * jxBrowser - it creates under chromium instance temporary user cache that is locked by single process, so when accessing from different instance it had some problem. 

then I was about to look at the `Single Angular Console` for all projects - which for me is more cleaner solution, where we will need to move start/stop logic from the project Level to the application level 

But looking at both gives me some ideas how to solve each, like the JXBrowser thing woudl be problem in both.
