### ISSUE TITLE
Support workspace creation flow in VSCode

### ISSUE THREAD

**Issue by olegdunkan** [nrwl/angular-console#630]
VS Code Version 1.33.0 (1.33.0) 
macOS 10.14: Mojave (Liberty)
Angular CLI Version: 7.4.5

There is no icon on the activity bar (at the left) and when I lunch it via Command Pallete (View Angular Console) the console isn't activated.

**Comment by fuadhasni** [comment]
Same Happening with VS Code 1.33.1 with node 10 on windows 8. 
standalone app working OK. 

output of ng vresion

Angular CLI: 7.3.3
Node: 10.15.1
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by jaysoo** [comment]
@olegdunkan @fuadhasni I think this is the same issue as #561 (the root of the workspace does not contain `angular.json`)

Can you confirm if this is the case?

**Comment by olegdunkan** [comment]
@jaysoo yes you are right, but it is strange behaviour, because when I installed it, my workspace was clean and I wish to apply Angular Console in order to create workspace. Now I have, first, to create angular.json in workspace and then reload VSCode and see Angular Console working.

**Comment by mrmeku** [comment]
@olegdunkan I've changed this bug's title to make it the tracking bug for workspace creation for our VSCode extension. That would address your last comment. We have other issues tracking having angular.json in a subdirectory

**Comment by jaysoo** [comment]
We've removed workspace creation from the revamped vscode extension. If/when we do add it back we'll consider the UX carefully.
