### ISSUE TITLE
Generate Tab: Mark command as favorite

### ISSUE THREAD

**Issue by fkolar** [nrwl/angular-console#636]
When you get to the **Generate**` '<>'` page, it lists so many schematics and their commands but if you use for your project on regular basics only let's say 4 (e.g.: component, directive, module, service), you have to scroll down and find them every time. 

When not to have a ability to mark command as favorite and move them up to the list?

**Comment by mrmeku** [comment]
This will be done! I just need to figure out the us treatment a little

**Comment by jaysoo** [comment]
Closing this issue since the new UX in vscode is quite different (e.g. we don't have a generate page).
