### ISSUE TITLE
Launch Icon Missing from Nav

### ISSUE THREAD

**Issue by profhess** [nrwl/angular-console#637]
In the demo/doc, it shows an icon on the left nav to click to invoke the plugin. My VS Code is missing that icon. Is it only invoked through the palette now?

**Comment by profhess** [comment]
FYI...just tried invoking through the palette and nothing occurred.

**Comment by OriginalDrTone** [comment]
I've noticed the same. No launch icon and can't launch it from the command palette.  MacOS.

**Comment by jaysoo** [comment]
@profhess is your workspace root the angular workspace? e.g. does `angular.json` exist at the root?

**Comment by OriginalDrTone** [comment]
> @profhess is your workspace root the angular workspace? e.g. does `angular.json` exist at the root?

In my case no.  Angular is in ClientApp foler of a root .NET Core project

**Comment by jaysoo** [comment]
@OriginalDrTone We currently only support cases where the root is the angular workspace. The current workaround is to open the the folder containing `angular.json` in vs code instead.

Going to close this as a duplicate of #561, but please re-open if the issue is different.

**Comment by profhess** [comment]
No it is not. I have the server side C# code included. I was unaware of that requirement.

[signature]

Clay Hess, MBA CSM
IT Faculty
715.803.1731
[seal-csm_sm]

**Comment by RaymsDev** [comment]
Same probleme here in angular project opened in WSL

![image](https://user-images.githubusercontent.com/14817349/60987930-eb28cf00-a342-11e9-8369-338be5ee7c77.png)
