### ISSUE TITLE
NVS Support

### ISSUE THREAD

**Issue by frederikdekegel** [nrwl/angular-console#641]
Wondering if Node Version Switcher (NVS) will be supported in a future version?

NVS, https://github.com/jasongin/nvs, by @jasongin, is a node version manager that supports Windows (without WSL), Mac, Linux and WSL. 
It also supports .node-version files so that the node version can be locked down in a project.

**Comment by mrmeku** [comment]
@frederikdekegel We have gone with NVM support for node version management. Would NVM fit your needs?

**Comment by frederikdekegel** [comment]
@mrmeku, thanks for your reply. 

The reason for me to ask for NVS support, is that NVS has support for Windows, while NVM has not. I know of the existence of nvm-windows. However, that one does not support .nvmrc files. NVS, has support for .node-version files, which allow automatic node version switching like nvm has.

So, in conclusion, if you want automatic node version throughout a file on Windows without WSL, than NVS is an option, NVM is not.

**Comment by mrmeku** [comment]
@frederikdekegel I'm definitely not opposed to adding support. Would you be willing to help implement the feature? I'd make myself available to answer any questions about the code base and help anyway I can

**Comment by frederikdekegel** [comment]
Willing yes ... Eligable no. I am primarily a .NET and Angular developer. My knowledge of nodejs is therefor close to zero. I tried to convince some colleagues with better understanding but I had no luck with that unfortunately. 

Is it possible from your end to implement this feature? Thx!

**Comment by mrmeku** [comment]
@frederikdekegel We don't have the engineering resources needed for us to want to implement and maintain this feature. But if its important to you I would be more than willing to aid you in creating a PR to add the functionality. If you're interested reopen the issue and we can coordinate
