### ISSUE TITLE
hide deprecated options

### ISSUE THREAD

**Issue by DmitryEfimenko** [nrwl/angular-console#644]
No need to display deprecated options. They only confuce people:
![deprecated](https://user-images.githubusercontent.com/2098175/56068409-8fdf4480-5d33-11e9-9c06-2205b41aa1ae.JPG)

**Comment by jaysoo** [comment]
I think we may still want to display them since they are still valid for use, but we should add `DEPRECATED` text to them.

@mrmeku What do you think? Perhaps we can put these options at the bottom as well?

**Comment by mrmeku** [comment]
@jaysoo We now have a UI hint which marks deprecated fields as deprecated. That should help things. @DmitryEfimenko Do you think that is a sufficient solution?

**Comment by DmitryEfimenko** [comment]
Thanks for all your hard work guys, the new VS Code Extension looks great!
The (deprecated) note definitely helps! Asking for anything more is kind of getting nit-picky. If you guys have bandwidth/desire to go a bit extra, I think sorting the deprecated options out of the way, towards the bottom of the page would also help. In either case, this issue can be closed

**Comment by jaysoo** [comment]
@DmitryEfimenko Glad you enjoy the new version and thanks for the feedback.! Will close this issue. :)
