### ISSUE TITLE
Close open port button

### ISSUE THREAD

**Issue by tayambamwanza** [nrwl/angular-console#652]
Sometimes when closing the app the angular port for serving is still open i.e localhost:4200, would it be possible to add a button that runs a script to close the port? I have to keep entering a script to close it manually before reserving the application. I'm on linux.

**Comment by mrmeku** [comment]
@tayambamwanza When you say `closing the app` can you be more specific? Do you mean shutting down `ng serve` or closing down angular console itself?

**Comment by tayambamwanza** [comment]
@mrmeku What I mean is after running `ng serve`, I let the app build to completion (100%), then I hit the `cancel` button when I try to serve again it gives me this error.
![Screenshot from 2019-04-16 01-17-00](https://user-images.githubusercontent.com/11971384/56171404-76652380-5fe5-11e9-8ec1-799c6091d2f2.png)

**Comment by mrmeku** [comment]
Thanks for that! Looks like we aren't killing the process cleanly. I'll get that tacken care of

**Comment by jaysoo** [comment]
This shouldn't be an issue with the revamped vscode extension.
