### ISSUE TITLE
Improve global error messaging

### ISSUE THREAD

**Issue by HackPoint** [nrwl/angular-console#653]
After opening a Console it's crashes all the time...

**Comment by jaysoo** [comment]
@HackPoint Can you help provide some info?

1. Are you using the VSCode extension or the standalone app?
2. Does Console stay open or crashes completely? A screenshot would be helpful.

**Comment by HackPoint** [comment]
@jaysoo Adding image


![111](https://user-images.githubusercontent.com/6758579/56357234-d0cbd300-61e3-11e9-8f5c-00406d76a076.png)

**Comment by HackPoint** [comment]
@jaysoo it happens all the time

**Comment by mrmeku** [comment]
@HackPoint Has pointed out that his console shuts down all the time with no debug information. We need to surface whatever useful information we can in order to make debugging issues easier.

**Comment by HackPoint** [comment]
![image](https://user-images.githubusercontent.com/6758579/57835136-98a9b700-77c6-11e9-9529-a31d6f0c9ac2.png)

After crashing it's not allowing to restart the console it's very unstable

**Comment by HackPoint** [comment]
@jaysoo unblock this issue please. It's impossible to use the console with such large amount of crashes.

**Comment by jbjhjm** [comment]
Not 1:1 the same issue but the same topic:
When angular.json becomes damaged, the console wont launch at all. It would be good to get an error message in this case.

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
