### ISSUE TITLE
Plea: disable the auto-play on the home page

### ISSUE THREAD

**Issue by ciel** [nrwl/angular-console#660]
You have one of the best programs out there for Angular, but every time I visit the `angularconsole.com` website, I'm greeted with a blasting YouTube narrative. Like, 0 is the number of times people want auto-play.

I implore you to disable this by default. I love Angular Console.

**Comment by mrmeku** [comment]
It shall be done! @JamesHenry Can you handle changing this behavior? I think we only need to change a bit of the url on the youtube video=

**Comment by JamesHenry** [comment]
@ciel @mrmeku this update was made, I can’t close the issue myself, but should be good to go now!
