### ISSUE TITLE
Release a snap version for Linux

### ISSUE THREAD

**Issue by tayambamwanza** [nrwl/angular-console#661]
Was wondering if instead of using a .deb package the Linux version could be a snap package on the snap store (vs code just did this recently), a summary of the benefits can be found in this article:

https://www.feliciano.tech/blog/what-are-linux-snap-packages-why-use-them/

**Comment by mrmeku** [comment]
We can definitely do this, thanks so much for the suggestion

**Comment by tayambamwanza** [comment]
#212 Is important for this as well

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
