### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Anganthier** [nrwl/angular-console#680]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `7.4.19`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/angular-console/files/3147327/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by mrmeku** [comment]
@kamilkisiela I've traced the CPU usage reported here to how Angular Console uses Apollo. We currently poll for updates for queries rather than using subscriptions. Can you please take a look at helping to lower CPU usage by migrating us from polling to subscriptions?

**Comment by mrmeku** [comment]
Should be fixed with https://github.com/nrwl/angular-console/pull/690
