### ISSUE TITLE
GraphQL error when app started

### ISSUE THREAD

**Issue by kavinda1995** [nrwl/angular-console#684]
When the app is starting. It gives this error.

GraphQL error: You passed an invalid value for the organization_id attribute. Invalid parameter. orgranization_id must be an integer

![graphql](https://user-images.githubusercontent.com/19621533/57504491-5be74700-7312-11e9-8149-1a67d49eeba7.PNG)

**Comment by Plondrein** [comment]
same error here

**Comment by kavinda1995** [comment]
It doesn't affect any workings (so far yet), but better to fix

**Comment by mrmeku** [comment]
I believe this is fixed now. If I'm mistaken please let me know
