### ISSUE TITLE
Can't start VSCode extension 

### ISSUE THREAD

**Issue by gxwilso** [nrwl/angular-console#699]
I installed the VSCode extension but it's not displayed in the activity bar. I tried Cmd-Shift-P and found View: Show Angular Console but it doesn't seem to so anything.

**Comment by mrmeku** [comment]
Sorry, we should have better docs on this. Angular Console will only show up if you open vscode to an angular cli workspace or have a workspace nested within the directory you have opened in your editor

We scan 4 directories deep, so either your project is very very nested or you just need to open a different directory to see the extension

Please reopen the issue if the above advice doesn't fix the issue for you
