### ISSUE TITLE
[feature]: Search in optional fields

### ISSUE THREAD

**Issue by bampakoa** [nrwl/angular-console#707]
It would be great if we could have the ability to search over optional fields when trying to execute a schematic command (e.g. `ng run build`) as the list is usually extensive and it is difficult to spot just a single option such as `statsJson `or `sourceMaps`.

**Comment by mrmeku** [comment]
Agreed. We have a whole new forms UI that we are getting ready and search plays a major role in it. Thanks for your suggestion and know it will be done soon

**Comment by bampakoa** [comment]
@mrmeku thanks very much for all your feedback!

**Comment by bampakoa** [comment]
Thanks very much for this feature @mrmeku
