### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tejasleo9** [nrwl/angular-console#710]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `7.4.30`
- OS Version: `Linux x64 4.15.0-50-generic`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/tejas/nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mrmeku** [comment]
We've made a number of performance improvements to console since Extension Version: 7.4.30
