### ISSUE TITLE
Angular-console is not showing up in visual code studio

### ISSUE THREAD

**Issue by sunnypranay** [nrwl/angular-console#721]
Hi,
Recently i am working with angular, I heard about angular console in visual studio. But when i tried to installed it in my vs code. It showed my successfully installed but when i am trying to open it, it's not responding.
I used following commands to open it like:
(I) f1 
(II) view->command pallet
I tried all of them nothing is working.
Thanks in advance ;-)

**Comment by tayambamwanza** [comment]
@sunnypranay I had this problem when creating a workspace for multiple angular apps and a library. 

e.g ~angular/projects/my-project.

When I opened the folder of the project "~angular/projects/my-project." it didn't show.

but when I opened the whole workspace "~angular/" then it showed so maybe try opening the folder before on top of "projects" folder and see if it shows.

**Comment by sunnypranay** [comment]
Thank you! So much got it !!!!
