### ISSUE TITLE
[vscode]: Terminal output display problem with PowerShell

### ISSUE THREAD

**Issue by bampakoa** [nrwl/angular-console#724]
Hey all,

I experience a weird problem using PowerShell as my preferred shell for VSCode.

When I open VSCode and toggle the integrated terminal, which is PowerShell in my case, the editor does not display any prompt unless I start typing (that's fine it should be a problem with VSCode and PowerShell generally).
But I suspect that this may have implications in the Angular Console because when I try to run a task and switch to the Terminal Output of the console, I do not see any feedback either.

If I open VSCode with integrated terminal closed and run a task of Angular Console everything works ok. Below you can see an animated image of the actual problem.

![powershell](https://user-images.githubusercontent.com/7170892/59417602-3c8b8000-8dd0-11e9-949e-c81303b04892.gif)

**Comment by mrmeku** [comment]
Thanks so much for the detailed bug report. I'll target fixing this ASAP for our next minor release this week.

**Comment by mrmeku** [comment]
@bampakoa This should be fixed now. If its not and I'm mistaken please let me know
