### ISSUE TITLE
VS Code 1.35.1 - Angular Console doesn't work

### ISSUE THREAD

**Issue by methodbox** [nrwl/angular-console#725]
Just as the title says. I installed the plugin but it doesn't appear on the side bar and selecting "View: Show Angular Console" from the command palette does nothing.

I'm on Windows at work but I'll try this on my Mac later, too.

**Comment by edunomatseye** [comment]
this is very true, as i encounter same challenge too.
Pls advise further.

**Comment by methodbox** [comment]
Closing this in favor of this: https://github.com/nrwl/angular-console/issues/705 as there is more activity (thought none yet from @nrwl).
