### ISSUE TITLE
No support for ng add @nrwl libraries 

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/angular-console#726]
Angular Console Version 8.0.0 (8.0.0)

I can not find any way of enabling the below capabilities when i create an empty workspace based on @nrwl/workspace and unless i open the project in the terminal and add it manually.

ng add @nrwl/angular # Adds Angular capabilities
ng add @nrwl/react # Adds React capabilities
ng add @nrwl/nest # Adds Nest capabilities
ng add @nrwl/express # Adds Express capabilities
ng add @nrwl/web # Adds Web capabilities
ng add @nrwl/node # Adds Node capabilities

**Comment by mrmeku** [comment]
Fixed as part of our latest release
