### ISSUE TITLE
Activity Bar Icon

### ISSUE THREAD

**Issue by theUseless** [nrwl/angular-console#728]
Issue Type: <b>Bug</b>

Angular Console Icon no longer visiable in the activity bar

Extension version: 8.0.5
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.88GB (6.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mrmeku** [comment]
This should be fixed with our latest release. We now always show Angular Console in the activity bar regardless of whether we were able to identify an angular CLI workspace or not
