### ISSUE TITLE
install in a folder other than %Appdata% 

### ISSUE THREAD

**Issue by bobsort** [nrwl/angular-console#729]
As title says, windows users normally don't install their applications in %AppData% folder specially when it is located on an SSD or M2 which is reserved for OS. 

There is no option during installation to change this folder as it immediately starts copying stuff in mentioned folder.

If it is not possible to provide a folder selection in installer, I would like to have a zip, tar package so I can unzip to any folder i like myself.

**Comment by mrmeku** [comment]
We will release a portable version of console for our next electron release to address this need.

https://www.electron.build/configuration/nsis#portable (for my own documentation)

**Comment by mrmeku** [comment]
Fixed by https://github.com/nrwl/angular-console/pull/805
