### ISSUE TITLE
Activity Button Removed?

### ISSUE THREAD

**Issue by Russ-McClelland** [nrwl/angular-console#730]
Message on a separate thread that I discovered because the same thing happened to me today. I was using the Activity and then need to restart my IDE. Did not come back. I tried reinstalling, etc. No idea how to add the button back into VSCode.

Was this removed recently? I can't seem to get VSCode to show it anymore and Im not sure how to get into the tool inside VSCode without it
<img width="1108" alt="Screen Shot 2019-04-04 at 7 13 03 PM" src="https://user-images.githubusercontent.com/6342882/55594470-c1418a00-570d-11e9-9f54-8d86032f8add.png">

_Originally posted by @mwight4 in https://github.com/nrwl/angular-console/issues/489#issuecomment-480095789_

**Comment by Raphzor** [comment]
Same trouble for me, just installed Angular Console, nothing appears.
Maybe VS Code changed some configuration on the Activity Bar? I can't open the extension by any other way also.

**Comment by mrmeku** [comment]
This should be fixed with our latest release. We now always show Angular Console in the activity bar regardless of whether we were able to identify an angular CLI workspace or not. Sorry for the trouble!
