### ISSUE TITLE
Permission denied error while creating new workspace

### ISSUE THREAD

**Issue by umairjameel321** [nrwl/angular-console#749]
My creating a new work space and while it creates a simple angular schematics angular app. It generates an error as shown in image below.

<img width="602" alt="Screenshot 2019-07-16 at 8 48 51 AM" src="https://user-images.githubusercontent.com/15831584/61265717-eaf95b00-a7aa-11e9-9812-e803876cf593.png">

I have tried upgrading npm and angular cli versions but still getting same error.

**Comment by mrmeku** [comment]
Will track as part of https://github.com/nrwl/angular-console/issues/749

Thanks for the debug information
