### ISSUE TITLE
Question in Create a new workspace cannot be answered

### ISSUE THREAD

**Issue by bobsort** [nrwl/angular-console#774]
When Creating workspace, there is a question in console capture asking:

hgow to change this setting, see http://angular.io/analytics, (y/N)

how to answer this question?
![ang](https://user-images.githubusercontent.com/2040435/61771249-eb849800-ae21-11e9-8614-5a76359ecf87.PNG)

**Comment by IvanPrytsko** [comment]
as a hot fix, run it before  `npm install -g @angular/cli @nrwl/schematics`

**Comment by mbriggs** [comment]
this should be fixed in the next release https://github.com/nrwl/angular-console/pull/757

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask.
