### ISSUE TITLE
Opening a new workspace: Causes "Error when reading the workspace data. Message: "Cannot convert undefined or null to object""

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/angular-console#779]
Hi,

I created a brand new workspace (for react) using

```
npx create-nx-workspace instant
```
all seemed to go well, asked me what type of app, i said React and then chose CSS.. Nothing special.

Now I try to open in angular console using "Open existing workspace" and produces

```
Error when reading the workspace data. Message: "Cannot convert undefined or null to object"
```

![image](https://user-images.githubusercontent.com/2370364/61990807-81e5d300-b047-11e9-957b-f15e709cb4e3.png)

I am using the latest create-nx-workspace as you can see I used NPX

and my version of angular console is the latest

![image](https://user-images.githubusercontent.com/2370364/61990815-a3df5580-b047-11e9-98c9-585db63877d7.png)

**Comment by appsolutegeek** [comment]
Erm! Missing angular.json using the create-nx-workspace command - even tried this as per the docs

```
npx create-nx-workspace@latest react-proj --preset react # Create a new workspace with a react app
ng g c home --style emotion
```

Gives also an error saying that the project isn't an angular workspace

**Comment by appsolutegeek** [comment]
I would probably suggest a better error, something in the lines of 

"angular.json" missing 

Directory is not part of a angular workspace 

etc

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

@appsolutegeek I have implemented that exact messaging as part of the vscode release. Thanks so much for the suggestion
