### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by MohamedAbdelkarim** [nrwl/angular-console#780]
- Issue Type: `Bug`
- Extension Name: `angular-console`
- Extension Version: `8.0.10`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.36.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/angular-console/files/3438367/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by jbjhjm** [comment]
Not sure if this is related to the issue I am experiencing.
Using vscode 1.36.1 and angular-console 8.0.10 the tab doesn't open at all, there's no reaction when clicking on one of the Angular console sidebar navigation menu items.
