### ISSUE TITLE
No options inside the vscode extension when using remote - ssh

### ISSUE THREAD

**Issue by SSmale** [nrwl/angular-console#787]
I am using a windows 10 machine to remote connect to a linux VM using the microsoft remote ssh extention package.

 the angular console side bar has been installed on the VM but when I click the sidebar i get all the taps but with no content inside them

**Comment by SSmale** [comment]
## Prerequisites 
Windows Machine with VS code insiders build
Linux VM running CentOS

## Steps
1. using Microsoft's Remote SSH extension connect from the windows machine to the remote server.
2. Install the Angular Console Extension on the windows machine and the VM 
3. open up an NX project on the VM via VScode  

Nothing shows in the tabs of the Angular Console extension

**Comment by mbriggs** [comment]
The issue here appears to be how we are generating our forms currently. The good news is that we are currently working on new implementations of our forms which are architected in a way that should not have this issue. Given that, this should (hopefully) become more functional as we release them :)

**Comment by mrmeku** [comment]
@SSmale This should be fixed now. I use angular console in a remote WSL shell all the time now and it seems to be working without failure :)
