### ISSUE TITLE
[Enhancement] Run-configurations

### ISSUE THREAD

**Issue by askarby** [nrwl/angular-console#794]
Having created a multi-app / lib NX-workspace, I'm using Angular Console (and it's great)... however, I keep finding myself doing the following things:

**To Develop**:

1. Click the "Run"-button next to the app
2. Click the "Serve"-button from the dropdown
3. Expand optional fields
4. Scroll down to the "HMR"-option
5. Click the dropdown
6. Select "true"
7. Click the "Run"-button (in the header)

It's 7 clicks... to serve.... SEVEN!

**To Test** (it's not as bad, but it's not great, either):

1. Click the "Run"-button next to the app
2. Click the "Test"-button from the dropdown
3. Scroll down to the "Watch"-option
4. Click the dropdown
5. Select "true"
6. Click the "Run"-button (in the header)

That's 7 clicks... to test.

**The suggestion:**

Make it so that you're able to save your configurations (settings to your options), so that they appear in the dropdown, that appear when clicking the "Run"-button (the first time)... that way, you can have it down to 2 clicks.

I hope it makes sense... If not, ask me, and I'll try to elaborate.

Thanks

**Comment by bampakoa** [comment]
@askarby you can edit `angular.json` in both cases to persist your configurations.

**To Develop**, you can add `"hmr": true`  in the `options` property of the `serve` target.
**To Test**, you can add `"watch": true`  in the `options` property of the `test` target.
