### ISSUE TITLE
Feature: expose `extension.angularConsole.generate` command

### ISSUE THREAD

**Issue by playerx** [nrwl/angular-console#795]
It would be great to have such command registered in vscode

Motivation:
To create key binding for Generate view

**Comment by playerx** [comment]
hi @mrmeku, let me share my current process first, how I use angular console for generating new component:
I don't have activity bar (`"workbench.activityBar.visible": false`) because it takes extra space, I've everything on keyboard shortcuts. 

So my first command is `Cmd+Shift+P`, 
next select `Angular Console: Focus on Navigation View`,
next click Generate
and after that start creating new component

The way I was thinking about simplifying this process was having one special keyboard shortcut in vscode to open Angular Console Generate View automatically, without additional steps. To achieve this I realized that there should be command in vscode: "angular console: show generate view", which will be available in keybindings.

**Comment by mrmeku** [comment]
@playerx I've got you covered. I have implemented a completely keyboard driven flow for you. I'll close this issue when we release next

**Comment by jaysoo** [comment]
It has been released as part of 9.0.0.
