### ISSUE TITLE
Creating new `Workspace` issue

### ISSUE THREAD

**Issue by HackPoint** [nrwl/angular-console#824]
Angular Console: 8.1.0
Typescript: 3.2.4
npm: 6.2.0
node: 10.9
node:v12.4.0
`/Applications/Angular Console.app/Contents/Resources/app/assets/new-workspace bodyspot --directory=bodyspot --collection=@nrwl/workspace --style=scss --no-skipInstall --no-skipGit --preset=full-stack --no-interactive
`
                                              bash: /Applications/Angular: No such file or directory

Process failed 🐳
`{data: {commands: [{,…}]}}
data: {commands: [{,…}]}
commands: [{,…}]
0: {,…}
command: "**/Applications/Angular Console**.app/Contents/Resources/app/assets/new-workspace bodyspot --directory=bodyspot --collection=@nrwl/workspace --style=scss --no-skipInstall --no-skipGit --preset=full-stack --no-interactive"
detailedStatus: null
id: "new-workspace bodyspot --directory=bodyspot --collection=@nrwl/workspace --style=scss --no-skipInstall --no-skipGit --preset=full-stack --no-interactive 1"
outChunk: ""
status: "in-progress"
workspace: null
__typename: "CommandResponse"`

The issue is with Space between the Angular Console.app how could it be fixed?

**Comment by hobbydevs** [comment]
same

**Comment by vdiaz1130** [comment]
I tried running the cmd straight in the terminal (manually escaping the space) and I get command not found:
```
/Applications/Angular\ Console.app/Contents/Resources/app/assets/new-workspace my-project
/Applications/Angular Console.app/Contents/Resources/app/assets/new-workspace: command not found
```

**Comment by guento** [comment]
same for me:
Angular Console Version 8.1.0 (8.1.0)
Mac OS: 10.14.6
node -v: 10.16.3
npm -v: 6.9.0

**Comment by HackPoint** [comment]
@guento I have found a workaround for this, it’s a bit lame but it works.
npm init nx-workspace myworkspace
After that you can take control over the solution from angular console, it’s lame, but it works.

**Comment by joelmuskwe** [comment]
Same Issue too

<img width="1015" alt="Screenshot 2019-09-09 at 08 29 43" src="https://user-images.githubusercontent.com/5989937/64507891-295b5400-d2dc-11e9-9b60-f3011bffef54.png">

**Comment by vdiaz1130** [comment]
@HackPoint I tried that. The workspace was created successfully but going back to Angular Console and attempting to open that new workspace gave me an error.

![image](https://user-images.githubusercontent.com/24530571/64577917-da4d0780-d34b-11e9-9ea1-d08837a37148.png)

**Comment by HackPoint** [comment]
@vdiaz1130 I havent met this issue. But if you want I can hook up via slack that way we can speak and work through this issue. Seems to be the NRWL to ignoring to solve the issues and they are trying to get more technologies into the console. But they forgot that they have to FIX the errors and bugs @vsavkin

**Comment by mrmeku** [comment]
We have decided to sunset our electron release of console so that we can better focus on high quality editor extension. That being the case I'm going to sadly close this bug with no plans to resolve the ask. 

We will be incorporating workspace creation into VSCode as part of our November release. Apologies for the delay/disappointing news with our decision to moonlight the electron release

**Comment by HackPoint** [comment]
@mrmeku  I'm not using Visual Studio Code. What solutions do you have  for us? I'm Intellij user.
@vsavkin @jeffbcross Someone?

**Comment by ytilis** [comment]
This works in 8.0, but doesn't in 8.1. Unfortunately, because Angular Console auto-updates, there's no way to stay on 8.0 after using it for the first time.

If you're going to abandon the only way to currently generate a new workspace using Angular Console, can you at the very least disable auto-updates, or remove the 8.1 electron release entirely, so that you don't force your users onto a broken version of an application you no longer have any intention of fixing?

**Comment by joelmuskwe** [comment]
@ytilis i totally agree and i think before making the decision to force vscode extension should have done a survey to find out what most people are using. i honestly never enjoyed using the extension as it kinda felt intrusive during development.

**Comment by HackPoint** [comment]
@ytilis and I’m using intellij I don’t want it to be plug-in in vscode.  Btw it doesn’t work as nice as its in the console in my Mac, looking too obtrusive and not comfortable to use as it’s as standalone app.
