### ISSUE TITLE
Blank screen after upgrading console to version 8.1.0

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/angular-console#826]
Just upgrade angular console on MacOS Mojave and now just getting a blank screen as shown below.
<img width="1016" alt="Screenshot 2019-09-05 at 23 59 43" src="https://user-images.githubusercontent.com/5989937/64386455-77046200-d039-11e9-8e64-f8d5d9d75636.png">

**Comment by danapsimer** [comment]
I'm getting the same result.  Using Mac OS X 10.14.6.

Things I have tried to fix this:

1. Downloaded the latest version form the website and copied it over the application
1. Deleted the "Library/Application Support/angular-console" Directory.
1. Deleted the application and copied it from the DMG again.
1. Rebooted my computer.

**Comment by danapsimer** [comment]
CMD+R will cause a refresh and show the UI.
