### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aessamm** [nrwl/angular-console#833]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `8.0.10`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\aessa\nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ViceIce** [comment]
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/angular-console/files/3627136/nrwl.angular-console-unresponsive.cpuprofile.txt)
