### ISSUE TITLE
Angular Console Crashes VS Code Extension Host

### ISSUE THREAD

**Issue by tthrash** [nrwl/angular-console#835]
This issue is similar to #834 as I'm also getting that issue, but on top of that, it is crashing VS Code extension host.

![Annotation 2019-09-16 095832](https://user-images.githubusercontent.com/15826510/64969406-75bd0b80-d869-11e9-9489-88c281473186.jpg)

![Annotation 2019-09-16 095943](https://user-images.githubusercontent.com/15826510/64969418-7a81bf80-d869-11e9-8e60-b2a70a17eee4.jpg)

**Comment by mrmeku** [comment]
@tthrash I'm not seeing anything within the screenshot that relates to angular console. The `console.ts` file is actually a part of vscode (I understand how the naming might have indicated a problem with this extension)

Are you sure angular console is causing this bug?

**Comment by tthrash** [comment]
@mrmeku Yes, I am sure. I reinstalled VS Code and added my extensions one at a time, once I added Angular Console extension host errored out. I removed Angular Console and all worked again.

**Comment by mrmeku** [comment]
Okay, that's good supporting evidence. Could you tell me some basic things about your system such as the operating system / version of vscode?

Also if vscode crashed when opening an open source project a link to the project would be great since I'd be better able to reproduce

Thanks for much for any details you can get @tthrash

**Comment by tthrash** [comment]
@mrmeku I just tried reinstalling it and it worked this time without crashing the extension host. However, Angular Console is having a performance issue.
![Annotation 2019-09-20 112536](https://user-images.githubusercontent.com/15826510/65343017-a7034780-db99-11e9-9a5f-2179e9e92134.jpg)

**Comment by mrmeku** [comment]
@tthrash Thanks for the update. Every release brings more core architecture improvements to console. I've focusing on speeding it up for 4 months now, it has just required a near complete rewrite of the product so its taken a long time. 

But thanks for baring with me and continuing to report issues as they come up. Its really helpful feedback

**Comment by mrmeku** [comment]
@tthrash I'm tracking the speed issue separately. If the extension host continues to crash due to console please reopen this issue
