### ISSUE TITLE
No content visible when connected to remote over SSH

### ISSUE THREAD

**Issue by haakomol** [nrwl/angular-console#836]
When using the SSH remote extension, no content is showing in the main content tab for Angular Console. It's the same result if clicking on "Settings", "DepGraph" or for example using Generate -> Component which was done here:

![angular-console-issue-no-webview-content-when-conntected-to-remote](https://user-images.githubusercontent.com/21310490/65393832-80563400-dd86-11e9-9494-66117aa864b8.PNG)

I assume you are using the Vebview API in the extension, and if so, the reason for the problem and how to fix it is explained here: https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api. I guess using the message passing API is the best way to go.

Sidenote: Atlassian's Jira and Bitbucket extension also has this issue. (It also doesn't install on the remote without editing it's setting.json.) It seems many extensions need to be tweaked to fully support the new remote feature for vscode, and new test suites might need to be added.

Update: I see that this is a duplicate of https://github.com/nrwl/angular-console/issues/787.

**Comment by mbriggs** [comment]
Thank you for the bug report! We are currently working on new implementations of our forms, and they do not access localhost directly. Given that, this should (hopefully) become more functional as we release them :)
