### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by WangZishi** [nrwl/angular-console#837]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `8.1.2`
- OS Version: `Windows_NT x64 10.0.18985`
- VSCode version: `1.38.1`

[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/angular-console/files/3647186/nrwl.angular-console-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mbriggs** [comment]
Hi, sorry to hear about this happening! Any information about what you were doing when this happened would be very useful for helping us debug it.

**Comment by jaysoo** [comment]
Closing due to lack of movement. We've rearchitected the vscode extension so performance should have improved. Please re-open if you continue to experience problems.
