### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by sylvain-pointud** [nrwl/angular-console#838]
Hello,
I got and error when I running a Build => Prod 
the command 

> ng build myProject --configuration=production --sourceMap=true --statsJson

the error in log

![image](https://user-images.githubusercontent.com/21316308/65521590-c2e45180-dee9-11e9-9e01-a0b5abca4bd5.png)

When I want to generate sourcemaps and statsjson , I use
> node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --source-map --stats-json

can we change angular console config to increase node max_old_space_size ?

**Comment by mbriggs** [comment]
As of node 8, it is possible to set that flag via environment variable. Curious if that would work for you 

`NODE_OPTIONS=--max_old_space_size=4096`

**Comment by sylvain-pointud** [comment]
Thank you:
In a powershell
[Environment]::SetEnvironmentVariable("NODE_OPTIONS", "--max_old_space_size=8192", "User")
