### ISSUE TITLE
Cannot return null for non-nullable field Settings.canCollectData.

### ISSUE THREAD

**Issue by TheFlyingCodeChimp** [nrwl/angular-console#850]
**VSCode** V1.38.1
**Angular Console Extenstion** V8.1.2
`ng new my-app`

On a fresh installation, when attempting to do anything using the console, I receive the error:

`Cannot return null for non-nullable field Settings.canCollectData.`

Is there a project setting it's expecting to find in the package.json?

**Comment by nixallover** [comment]
@TheFlyingCodeChimp thanks for letting us know! I'll bring this up to the team and update you when I know more.

**Comment by mrmeku** [comment]
This issue pertains to the old electron version of the code base. We have completely removed our graphql endpoint from our vscode extension at this point in time
