### ISSUE TITLE
#821 still not fixed. VSCode extension still failing with pathing issue.

### ISSUE THREAD

**Issue by urwrstkn8mare** [nrwl/angular-console#851]
Sorry for creating another issue with the same topic but I have the same issue as them (https://github.com/nrwl/angular-console/issues/821)  and it doesn't seem to be fixed. I am on windows using Angular Console version 8.1.2. I am almost certain this issue is caused by spaces in paths. I think an easy fix would include quotes around the path when executing but I don't know maybe it is more complicated than it looks. All I know is if I execute the same command in PowerShell but just with quotes around them so it doesn't mistake the path as two arguments, it works. It is probably best if before executing anything using paths you should put quotes around them just in case the path has a space in it. This solution would fix it across all platforms I am pretty sure because they all support quotes around paths.

**Comment by nixallover** [comment]
@urwrstkn8mare Thanks for bringing this to our attention. I opened #821 again, the team will post further updates there.
