### ISSUE TITLE
Cannot generate component inside folder with space in its name.

### ISSUE THREAD

**Issue by lueenavarro** [nrwl/angular-console#857]
I go to Angular console in VS Code
then Generate
then search for component

this is what I see in my terminal
```
> Executing task: c:\Users\lnavarro6\OneDrive - XXX Production\Desktop\app-name\node_modules\.bin\ng.cmd generate @schematics/angular:component --dry-run --no-interactive <

c:\Users\lnavarro6\OneDrive\ : The term 'c:\Users\lnavarro6\OneDrive\' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
+ & {c:\Users\lnavarro6\OneDrive\ -\ XXX\ Production\Desktop\app-name\no ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Users\lnavarro6\OneDrive\:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I understand that the error is because of `OneDrive - XXX Production` but I cannot change the folder name to something else since its auto-generated by Microsoft

**Comment by JanneHarju** [comment]
this is already reported here https://github.com/nrwl/angular-console/issues/821

**Comment by mrmeku** [comment]
Sorry this took me so long to figure out. I had no idea how to escape spaces in powershell until now. You have to use backticks instead of the unix style / character.

**Comment by jaysoo** [comment]
This should be fixed now. Please re-open if the issue persist for you.
