### ISSUE TITLE
Coin Miner detected by Windows defender

### ISSUE THREAD

**Issue by Maryannah** [nrwl/angular-console#864]
Hello,

My antivirus (Windows Defender) detected a coin miner in the Angular console folder : 

![image](https://user-images.githubusercontent.com/46892394/67616135-548afb80-f7d5-11e9-87bf-786a311a48ba.png)

**I'm not saying you put it there** (in fact I'm not even sure where it is, I don't understand the path given), but this is a very pristine computer and it seems to come from a dependency. 

Would you have any information about that ? 

Thank you in advance !

**Comment by jaysoo** [comment]
@Maryannah Hi, thanks for the report. Did you download a fresh copy of the Console from angularconsole.com? If not, I'd suggest you uninstall and then install a fresh download.

There was an old vulnerability related to one of our dependencies, but this had been patched a while ago.

**Comment by Maryannah** [comment]
@jaysoo indeed, the version I have is rather old (I'm not using this PC to code anymore). 

Glad to know that then, thank you for your time ! Feel free to close this issue as resolved :)
