### ISSUE TITLE
Feature: Added feature module

### ISSUE THREAD

**Issue by jiayisheji** [nrwl/angular-console#873]
Can I add a feature to quickly generate feature modules?
Contains feature modules, routing modules, components, directives, pipes, guards, services, interfaces, models, enumerations, dto classes and other files

Example:
- Name
- Project
- SkipTests = true | false
- Routing = true | false
- Directive = true | false
- Enum = true | false
- Guard = true | false
- Model = true | false
- Interface = true | false
- Dto = true | false
- Pipe = true | false
- Service = true | false

You can save time generating these files

**Comment by mrmeku** [comment]
@jiayisheji The way to do this is by creating your own workspace schematics. If you use NX with the angular CLI you can follow this guide to make your own: https://medium.com/@simonb90/create-workspace-specific-schematics-with-nrwl-nx-9a1b7cd65345

Angular console currently has a hook to `ng add` extensions to the CLI so if you were to publish a schematic set which generate modules in the form you are looking for then we could add it to our extensions section.

Angular console isn't meant to provide schematics but rather is meant to make it easier to add other schematics that others in the community have produced. Does that make sense?

**Comment by jiayisheji** [comment]
@mrmeku Thank you very much for your reply. Recently, I have been working on the feature of create @workspace-schematics

**Comment by jaysoo** [comment]
Closing this issue since it out of scope for Angular Console.
