### ISSUE TITLE
Desktop version not available?

### ISSUE THREAD

**Issue by WHairstonLOI** [nrwl/angular-console#879]
I don't see a download link for the Windows desktop version at https://angularconsole.com/#download, only a button to download the VS Code version. Is the desktop version discontinued? I had an old copy of the desktop v7.1.0 that I was hoping to upgrade.

**Comment by tja4472** [comment]
Afraid not.

https://blog.nrwl.io/brand-new-ui-custom-vscode-task-support-more-in-angular-console-9-0-5e4d3a109fb9

> The Future of Angular Console
The end of our electron app
It is with a sad heart that I inform you that we’re no longer supporting our electron release of Angular Console.

**Comment by WHairstonLOI** [comment]
LOL - It figures I'd decide to retackle my noob Angular project after with some updated tools and I missed this announcement by 1 day!

A couple of suggestions and questions:

1. Please consider noting this on the angularconsole.com web site (possibly by providing a link to the blog entry in the Download section).

2. Please update the instructions on the main Github page (https://github.com/nrwl/angular-console) in the Download section that state: "If you aren't a VSCode user, download a standalone desktop application at angularconsole.com."

3. Is it possible to make available for download the previously-published desktop versions of the software (with sufficient warnings/notifications that it's no longer being updated)? (I'll still keep using my v7.1.0 for now, but would prefer to have any updates published since then.)

4. Is there any way to make the VSCode plugin work as a Visual Studio Professional plugin?

5. Is there any consideration for making the desktop version available as a separate open-source project (even if it's under a different name and/or different maintainers)? There are a lot of relatively-recent third-party articles that still point to this tool as something that helps simplify development; it's really disappointing to get excited about this tool from an article only to find out that it's no longer available.

Thanks!

**Comment by jaysoo** [comment]
@WHairstonLOI We've updated angularconsole.com to only include the vscode version since we're no longer maintaining the desktop version.

For now anyone interested in the desktop app still can download from the releases page. https://github.com/nrwl/angular-console/releases

We can add a section in the readme to link to the releases page.
