### ISSUE TITLE
Deploy command is invalid

### ISSUE THREAD

**Issue by smarth55** [nrwl/angular-console#880]
After the update to the VSCode plugin, the deploy command that can be selected from the Angular Console > Navigation does not run. I can see that when I try to run it, the terminal outputs `Executing task: ng deploy my-app <`
but errors with `The specified command ("deploy") is invalid.`

I can, however, select the run command and the choose the deploy command from that menu and get `Executing task: ng run my-app:deploy <` which does work.

Just a minor inconvenience as long as it still deploys, but still confusing.

**Comment by isaacplmann** [comment]
Good catch.  I can reproduce that as well.  The `ng deploy my-app` command should be `ng run my-app:deploy`.

The short-hand version works for `serve`, `build` and `test`, but not for  tasks that haven't been hard coded by the Angular CLI.

**Comment by mrmeku** [comment]
Ah that makes sense. Deploy is hard coded in later version of the cli but not in some earlier ones. We can change things so that deploy doesn't use the short hand syntax so that we can support older versions of the CLI

**Comment by jaysoo** [comment]
Thanks for the bug report. This will be fixed in the next patch release.
