### ISSUE TITLE
VSCode Prompting for Angular.json

### ISSUE THREAD

**Issue by jfreal** [nrwl/angular-console#893]
After a fresh new install I'm being prompted for the location of angular.json.

![image](https://user-images.githubusercontent.com/144533/68976210-4b34f380-07c3-11ea-8dba-03597d08cd1d.png)

**Comment by Jcather** [comment]
I'm having the same issue / equally confused by the UI. It's totally different to all tutorials online. Have you made any headway yet ?

**Comment by jfreal** [comment]
If you download the angular.json file from the source you can use that.  What I think happens is a new workspace is created wherever you have a angular.json file.

**Comment by pawelprochnicki** [comment]
I'm having the same issue. What a pity :-( It doesn't work. I have OSx Catalina and VS 1.40 angular CLI 8.3.9, and I only see "select angular.json" and it doesn't seem to do anything after manually selecting the .json file.

**Comment by jaysoo** [comment]
@jfreal We try to detect `angular.json` at your workspace root, but if we cannot load it then we show this prompt.

Is the extension not loading the `angular.json` file even after manually selecting it?

**Comment by jaysoo** [comment]
If anyone has an `angular.json` file that they don't mind sharing, can you link it here so we can take a look?

**Comment by jfreal** [comment]
I understand now.  Your angular.json is generated by the CLR when you create a new project.

I don't think this is a bug, but an opportunity to update the documentation with clear instructions on how to start a new project.
