### ISSUE TITLE
Use PATH to resolve bash 

### ISSUE THREAD

**Issue by rweng** [nrwl/angular-console#898]
Hi, I've noticed the path `/bin/bash` is hardcoded when executing commands.

https://github.com/nrwl/angular-console/blob/919ca164daba1f73bee6c62f042c481b9c616797/apps/vscode/src/app/ng-task/shell-execution.ts#L40-L50

This caused my `.bash_profile` to fail, since it assumed the newer, brew installed bash at `/usr/local/bin/bash`.

I've now linked `/bin/bash` to this bash. Maybe that is common practice anyway, though I'm not sure how it behaves on system updates.

In any case, maybe the user configured shell ($SHELL?) should be used?

**Comment by jaysoo** [comment]
@rweng Thanks for the report. What errors did you see when it was pointing to the old `/bin/bash`?

**Comment by rweng** [comment]
I was trying to set multiple shell options in my `.bash_profile` with `shopt -s`.  I think it was `globstar` and `autocd` which was not available on the default OS X bash.
