### ISSUE TITLE
Unexpected token in JSON at position 1510

### ISSUE THREAD

**Issue by vincentpalita** [nrwl/angular-console#900]
When I have a dependency in my package.json file that is a local path written with a prefix `./` it makes Angular Console not load any schematics and totally fail on any action.
Removing the `./` make Angular Console works.

Does not work:
`"dependency-name": "./local-node-modules/dependency-name"`

Works:
`"dependency-name": "local-node-modules/dependency-name"`

The prefix `./` is valid following the npm documentation: https://docs.npmjs.com/files/package.json#local-paths

**Comment by jaysoo** [comment]
@vincentpalita Thanks for the report, we'll get this fixed up next release!

**Comment by mrmeku** [comment]
@vincentpalita I looked through the code base and it doesn't seem like angular console has any logic to parse your local anglular JSON. The error you specified in your issue report comes up when we parse your `angular.json` file. I haven't been able to reproduce the error in any case. 

Would you be able to come up with a reproduction of the issue? It would be really helpful. Thanks!

**Comment by vincentpalita** [comment]
@mrmeku Sorry for getting back to you that late. I have tried to reproduce the error, but couldn't.
Sorry to make you loose time with that issue.
