### ISSUE TITLE
type and name are reversed in interface generation

### ISSUE THREAD

**Issue by GreatHawkeye** [nrwl/angular-console#906]
Hi,

It looks like the `type` and `name` fields are reversed :

![image](https://user-images.githubusercontent.com/29467803/69486198-8aa9b280-0e49-11ea-82d6-2d4496550775.png)

As you can see, I'm typing `interface` in the `type` field and `list` in the name field and the `dry-run` outputs `[...]interface.list.ts` when it should outputs `[...]list.interface.ts`

**Comment by jaysoo** [comment]
Thanks for the report, we'll get this patched up!
