### ISSUE TITLE
[schematic] generate

### ISSUE THREAD

**Issue by maxisam** [nrwl/angular-console#908]
If the property in schema is set as visible: false

https://github.com/ngrx/platform/blob/c9d1f23c6770b2470b97ce6a8683dc754bad4505/modules/schematics/src/feature/schema.json#L11

there is no way to set the property through UI

However, it is nice to set things like path or UI should pick up the path from explorer ui.

**Comment by jaysoo** [comment]
@maxisam Thanks for reporting the issue. We'll look into it.
