### ISSUE TITLE
Autocomplete module name errors: path does not exist.

### ISSUE THREAD

**Issue by Yonet** [nrwl/angular-console#91]
<img width="804" alt="screen shot 2018-08-07 at 5 27 49 pm" src="https://user-images.githubusercontent.com/3523671/43810482-c4667938-9a6c-11e8-83db-3aeed6cbe1f2.png">

**Comment by ndcunningham** [comment]
As a work-around you can copy and paste the path which is in the auto-complete suggestion until it is fixed

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/angular-console/commit/c51668065aac503bcfe20c58c22d043fc948db8b
