### ISSUE TITLE
Terminal shows "command is missing required fields" when clicking Optional fields

### ISSUE THREAD

**Issue by jschwarty** [nrwl/angular-console#94]
Steps to reproduce:

1. Go to a workspace
2. Go to **Generate Code**
3. Click on the Angular CLI **Component** schematic
![ac-schematic-issue-1](https://user-images.githubusercontent.com/1243236/43852578-6eba6040-9af2-11e8-9f8b-c142ade41221.png)
4. See that the terminal output is fine
![ac-schematic-issue-2](https://user-images.githubusercontent.com/1243236/43852583-717b85b6-9af2-11e8-89b7-93340b5836a4.png)
5. Click on the **Optional fields** bar to expand
![ac-schematic-issue-3](https://user-images.githubusercontent.com/1243236/43852587-73711d90-9af2-11e8-8bd9-d5a33d0463e9.png)
6. See that the terminal has "command is missing required fields"
![ac-schematic-issue-4](https://user-images.githubusercontent.com/1243236/43852592-757400bc-9af2-11e8-95d5-8a8e203ad821.png)

**Comment by mrmeku** [comment]
@jschwarty What do you think it should show? Nothing at all?

**Comment by jschwarty** [comment]
My expectation is that nothing would change in the terminal output when I just expand a part of the UI (and not actually selecting/focusing any one of the option fields).

**Comment by mrmeku** [comment]
Cool, it shall be done then

**Comment by ViceIce** [comment]
The console should not output while fields are required and /or invalid.

**Comment by mrmeku** [comment]
This bug applies to the now deprecated electron version of console
