### ISSUE TITLE
skipPackageJson option installs packages

### ISSUE THREAD

**Issue by Yonet** [nrwl/angular-console#95]
This is not a bug but confusing behavior. 

Run:
```
ng generate library teach/app1 --publishable --skipPackageJson --routing --lazy --parentModule=apps/teach/src/app/app.module.ts
```
Behavior:

@angular-devkit/build-ng-packagr, ng-packagr, tsickle, tslib installed.
npm warnings displayed. 

Suggestion: 
I do see that these packages are being installed for publishable option but it might be confusing to users. I am wondering if we can display more information on what is happening?

<img width="799" alt="screen shot 2018-08-08 at 12 51 41 pm" src="https://user-images.githubusercontent.com/3523671/43861135-caef9660-9b0a-11e8-8c2a-4388026b2668.png">
<img width="789" alt="screen shot 2018-08-08 at 12 51 55 pm" src="https://user-images.githubusercontent.com/3523671/43861141-ce8e5888-9b0a-11e8-9d67-bb78887ce9d4.png">

**Comment by mrmeku** [comment]
@Yonet I think that we'll need to fix this as a part of our schematic itself rather than anything Angular console is doing. Could you file the issue their so @FrozenPandaz can take a look?
