### ISSUE TITLE
Schematic is not available on Generate Code List, after adding a schematic extension.

### ISSUE THREAD

**Issue by Yonet** [nrwl/angular-console#96]
Repro:
-Navigate to add/remove extension.
- Add a new extension from the list. Ex: angular/material
- Navigate to generate code tab.
- Scroll down or filter by schematics name.
<img width="938" alt="screen shot 2018-08-08 at 1 45 56 pm" src="https://user-images.githubusercontent.com/3523671/43865012-1fab15c0-9b16-11e8-8a2a-1cc41f51597c.png">
<img width="940" alt="screen shot 2018-08-08 at 1 45 42 pm" src="https://user-images.githubusercontent.com/3523671/43865019-2300df20-9b16-11e8-84ed-8f474430f540.png">

**Comment by jibbers42** [comment]
Is there a workaround to get console to show schematics other than `@schematics/angular` after importing a project, or do we simply need to wait for this fix? I'm on Ubuntu if it matters.

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/angular-console/commit/1b98dd9feb91679c0339b237896d6764ee8dae89

Thank you!
