### ISSUE TITLE
Add @nrwl/schematics error to an existing Angular 6 project

### ISSUE THREAD

**Issue by Yonet** [nrwl/angular-console#99]
Retro:
- Open the project.
- Navigate to add extension. 
- Choose @nrwl/schematics and run.

Error:
<img width="800" alt="screen shot 2018-08-08 at 7 07 37 pm" src="https://user-images.githubusercontent.com/3523671/43874048-62cd81e4-9b3e-11e8-854a-e4f3a7265da7.png">

Repro repo diff:
https://github.com/Yonet/Code4Good/commit/dac9b89d7cede41b9b979a3077265b9fc47e373c

**Comment by mrmeku** [comment]
This is an issue with the ng add implementation of @nrwl/nx. Please file a bug against that repo instead: https://github.com/nrwl/nx/issues
